import {escapeHTML as e} from '../config.js';import {tournamentMatches,tournamentRounds,tournamentStandings} from '../tournament.js';const $=id=>document.getElementById(id);
export class TournamentMenu{
 constructor(app){this.app=app;this.stage='choose';this.teamId='';this.matchId='';this.divisionId='';this.results={};}
 tournament(){return this.app.data.tournament(this.app.settings.value.season)}
 teams(){return this.app.data.tournamentTeams(this.app.settings.value.season)}
 options(){const t=this.tournament();const group=tournamentMatches(t).filter(m=>m.homeTeamId&&m.awayTeamId);const playoff=tournamentRounds(t).flatMap(r=>(r.matches||[]).map((m,i)=>({...m,id:m.id||'playoff-'+t.season+'-'+r.name.replace(/\W/g,'')+'-'+i,round:r.name})));const all=[...group,...playoff].filter(m=>m.homeTeamId&&m.awayTeamId),seen=new Set();return all.filter(m=>{const key=[m.round||'Group Stage',m.homeTeamId,m.awayTeamId].join('|');if(seen.has(key))return false;seen.add(key);return true})}
 selectedMatch(){return this.options().find(m=>m.id===this.matchId)||null}
 prepare(){if(this.app.mode!=='tournament')return;const saved=this.app.settings.value.tournamentTeam,teams=this.teams();this.teamId=teams.some(t=>t.id===saved)?saved:teams[0]?.id||'';this.stage='choose';this.matchId='';this.results={};}
 afterGame(match){if(match?.tournament)this.results[match.tournament.id]={home:match.stats[0].goals,away:match.stats[1].goals};this.stage='schedule';this.matchId='';}
 setTeam(id){this.teamId=id;this.app.settings.set('tournamentTeam',id);}
 team(id){const team=this.teams().find(t=>t.id===id);return this.app.formation?.teamForMatch(team)||team}
 nextForUser(){return this.options().find(m=>(m.homeTeamId===this.teamId||m.awayTeamId===this.teamId)&&!this.results[m.id])||null}
 applyPair(m){const home=this.team(m.homeTeamId),away=this.team(m.awayTeamId);if(!home||!away)return false;const user=home.id===this.teamId?home:away,cpu=user===home?away:home;this.app.selected={user,cpu};this.app.saveSelection();this.matchId=m.id;return true}
 continue(){if(this.stage==='choose'){this.stage='lineup';this.render();return}if(this.stage==='lineup'){this.stage='schedule';this.render();return}}
 simulate(){const next=this.options().find(m=>!this.results[m.id]&&(m.homeTeamId!==this.teamId&&m.awayTeamId!==this.teamId));if(next){this.results[next.id]={home:Number.isFinite(next.homeScore)?next.homeScore:Math.floor(Math.random()*3),away:Number.isFinite(next.awayScore)?next.awayScore:Math.floor(Math.random()*3)};this.render()}}
 play(m){if(this.applyPair(m))this.app.start()}
 render(){const active=this.app.mode==='tournament',flow=$('tournament-flow');flow.hidden=!active;document.querySelector('.versus-layout').hidden=active;document.querySelector('.selection-footer').hidden=active;$('tournament-controls').hidden=true;if(!active)return;const t=this.tournament(),teams=this.teams();$('selection-mode').textContent='TOURNAMENT MODE';$('selection-title').textContent='INTER-MADRASAH TOURNAMENT.';$('selection-description').textContent='Choose your institution, manage the matchday schedule, and chase the final.';if(this.stage==='choose'){flow.innerHTML='<section class="tournament-flow-card"><span class="eyebrow">INTER-MADRASAH TOURNAMENT · '+e(t.season)+'</span><h2>CHOOSE YOUR TEAM</h2><p>Select the institution you will represent. Your division and tournament path stay with the selected season.</p><div class="tournament-team-grid">'+(t.divisions||[]).map(d=>'<div class="tournament-division"><h3>'+e(d.name||d.id)+'</h3><div>'+d.teams.map(raw=>{const x=teams.find(z=>z.id===raw.id);return '<button class="tournament-team-choice '+(x?.id===this.teamId?'active':'')+'" data-team="'+e(raw.id)+'"><span class="team-choice-mark"><img src="'+e(x?.logo||raw.logo||'assets/lsl-logo.png')+'" alt="" loading="lazy"></span><span><strong>'+e(raw.name)+'</strong><small>'+((x?.lineup||[]).length?x.lineup.length+' starters · '+(x.bench?.length||0)+' bench':'Roster pending')+'</small></span></button>'}).join('')+'</div></div>').join('')+'</div><div class="tournament-flow-actions"><button data-open-formation class="secondary">FORMATION / LINEUP BUILDER</button><button id="tournament-continue" class="primary">CONTINUE TO LINEUP →</button></div></section>'}
 else if(this.stage==='lineup'){const team=this.team(this.teamId),division=team?.division||'Inter-Madrasah';flow.innerHTML='<section class="tournament-flow-card"><span class="eyebrow">'+e(t.season)+' · '+e(division)+'</span><div class="tournament-inline-logo"><img src="'+e(team?.logo||'assets/lsl-logo.png')+'" alt="" loading="lazy"></div><h2>'+e(team?.name||'YOUR TEAM')+' <small>LINEUP · '+e(this.app.formation?.labelFor(team)||'2 — 2 — 2')+'</small></h2><p>Starting seven selected from the published tournament roster. Missing names are shown as Player1, Player2 and so on.</p><div class="formation-board"><div class="formation-row"><span>GK</span></div><div class="formation-row"><span>DEF</span><span>DEF</span></div><div class="formation-row"><span>MID</span><span>MID</span></div><div class="formation-row"><span>FWD</span><span>FWD</span></div></div><ol class="tournament-lineup">'+(team?.lineup||[]).map(p=>'<li><b>'+e(p.role)+'</b><span>'+e(p.name)+'</span><small>'+e(p.jersey?'#'+p.jersey:'PLAYER')+'</small></li>').join('')+'</ol><div class="tournament-flow-actions"><button data-open-formation class="secondary">EDIT FORMATION / LINEUP</button><button id="tournament-continue" class="primary">CONTINUE TO SCHEDULE →</button></div></section>'}
 else {const next=this.nextForUser(),schedule=[...this.options()];flow.innerHTML='<section class="tournament-flow-card tournament-schedule-card"><div class="tournament-schedule-head"><div><span class="eyebrow">INTER-MADRASAH TOURNAMENT · '+e(t.season)+'</span><h2>TOURNAMENT SCHEDULE</h2><p>'+(next?'Simulate other fixtures until your next match.':'Your listed fixtures are complete.')+'</p></div><div class="tournament-schedule-actions">'+(next?'<button id="tournament-play" class="primary">PLAY GAME →</button>':'')+'<button id="tournament-simulate" class="secondary" '+(!schedule.some(m=>!this.results[m.id]&&m.homeTeamId!==this.teamId&&m.awayTeamId!==this.teamId)?'disabled':'')+'>SIMULATE GAME</button></div></div><div class="tournament-schedule-list">'+schedule.map(m=>{const mine=m.homeTeamId===this.teamId||m.awayTeamId===this.teamId,played=this.results[m.id],score=played?played.home+' : '+played.away:'— : —';return '<div class="tournament-fixture '+(mine?'mine ':'')+(next?.id===m.id?'next ':'')+'"><span>'+e(m.round||'Group Stage')+'</span><strong>'+e(m.homeTeamName||'Team')+' <b>'+score+'</b> '+e(m.awayTeamName||'Team')+'</strong><small>'+ (played?(mine?'YOUR RESULT':'SIMULATED'):(mine?'YOUR FIXTURE':'UPCOMING'))+'</small></div>'}).join('')+'</div><div class="tournament-dashboard"><section><h3>GROUP STANDINGS</h3><div class="division-tabs">'+(t.divisions||[]).map(d=>'<button data-division="'+e(d.id)+'" class="'+(d.id===(this.divisionId||t.divisions[0]?.id)?'active':'')+'">'+e(d.name||d.id)+'</button>').join('')+'</div><div class="standing-mini">'+tournamentStandings(t,this.divisionId||t.divisions[0]?.id).map((r,i)=>'<div><b>'+ (i+1)+'</b><span>'+e(r.name)+'</span><strong>'+r.pts+' pts</strong><small>'+r.w+'W '+r.d+'D '+r.l+'L</small></div>').join('')+'</div></section><section><h3>PLAYOFF BRACKET</h3><div class="bracket-mini">'+tournamentRounds(t).map(r=>'<article><strong>'+e(r.name)+'</strong>'+(r.matches||[]).map(m=>'<div class="bracket-match"><span>'+e(m.homeTeamName||'TBD')+'</span><b>'+((m.homeScore??'–')+' : '+(m.awayScore??'–'))+'</b><span>'+e(m.awayTeamName||'TBD')+'</span></div>').join('')+'</article>').join('')+'</div></section></div></section>'}
 flow.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{this.setTeam(b.dataset.team);this.render()});flow.querySelector('#tournament-continue')?.addEventListener('click',()=>this.continue());flow.querySelector('#tournament-simulate')?.addEventListener('click',()=>this.simulate());flow.querySelector('#tournament-play')?.addEventListener('click',()=>this.play(this.nextForUser()));flow.querySelectorAll('[data-division]').forEach(b=>b.onclick=()=>{this.divisionId=b.dataset.division;this.render()});}
}
