import {busyAction,confirmAction,copyRoomCode} from './ui.js';
import {LiveService} from './service.js';
import {LivePeer} from './peer.js';
import {LiveArena,traceDigest} from './arena.js';
import {LeagueData} from '../data.js';
import {MATCH_DURATIONS} from '../match-options.js';
import {FORMATION_ORDER,presetSlots} from '../formation.js';
import {buildSquad} from './simulation.js';
import {escapeHTML as e,clockText} from '../config.js';
import {playerLabel} from '../player-label.js';
const $=id=>document.getElementById(id),root=$('live-app');
const service=new LiveService(error=>toast(error.message)),league=new LeagueData();
let current=null,roomStop=null,peer=null,arena=null,tab='create',rooms=[],invites=[],recent=[],people=[],roomCache=new Map(),presence=new Map(),observed=new Set(),popupId=null,renderKey='',reconnecting=0,connectionEpoch=-1,finishing=false;
const deferredRequests=new Set();
const activeStates=['STARTING','LIVE','CLOSE TO END'];
function toast(message){const el=$('live-toast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,6500);}
async function task(fn){try{return await fn();}catch(error){toast(error.message||'Connection failed. Please try again.');return null;}}
const status=r=>`<span class="live-status" data-status="${e(r?.status||'OFFLINE')}">${e(r?.status||'OFFLINE')}${r&&['LIVE','CLOSE TO END'].includes(r.status)?' · '+clockText(r.status==='CLOSE TO END'?r.remaining:r.elapsed):''}</span>`;
function roomCard(r){return `<article class="live-room"><div>${status(r)}<h3>${e(r.code)}</h3><small>HOST · ${e(r.names[r.host])}</small>${r.guest?`<p>${e(r.choices[r.host]?.name||r.names[r.host])} <strong>${r.score.join(' – ')}</strong> ${e(r.choices[r.guest]?.name||r.names[r.guest])}</p>`:'<p>Waiting for player…</p>'}${r.endReason?`<p>${e(r.endReason)}</p>`:''}</div><button class="hub-button" data-room="${e(r.code)}">${r.status==='FULL TIME'?'RESULT':'OPEN ROOM'}</button></article>`;}
function watchOther(code){if(!code||observed.has(code))return;observed.add(code);service.watchRoom(code,r=>{if(r)roomCache.set(code,r);renderLists();});}
function gate(){root.innerHTML=`<section class="live-hero"><div><span class="eyebrow">TWO PLAYERS · ONE PITCH</span><h1>LIVE HEAD<br>TO HEAD</h1><p>Your account. Your starting seven. A real opponent, in a private room you control.</p></div></section><section class="live-panel" style="max-width:520px"><h2>Welcome to live matchday</h2><p>Sign in to your Lantern Rush account. Existing usernames and six-digit passcodes work here after online services are deployed.</p><form id="live-login" class="live-form"><label>USERNAME<input name="username" minlength="2" maxlength="12" autocomplete="username" required pattern="[A-Za-z0-9_]{2,12}"></label><label>SIX-DIGIT PASSCODE<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{6}" minlength="6" maxlength="6" autocomplete="current-password" required></label><div class="live-actions"><button class="hub-button primary" value="login">SIGN IN</button><button class="hub-button" value="create">CREATE ACCOUNT</button></div><p id="sign-feedback" role="status"></p></form></section>`;
 $('live-login').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,b=event.submitter;if(form.dataset.busy)return;form.dataset.busy='true';const buttons=[...form.querySelectorAll('button')];buttons.forEach(button=>button.disabled=true);const feedback=$('sign-feedback');feedback.textContent='Verifying your account...';try{await service.signIn(form.elements.username.value,form.elements.pin.value,b?.value==='create');form.elements.pin.value='';await enter();}catch(error){if(feedback.isConnected)feedback.textContent=error.message;else toast(error.message);}finally{delete form.dataset.busy;buttons.forEach(button=>button.disabled=false);}};
}
async function enter(){
 home();people=await service.people();
 service.watchRooms(value=>{rooms=value;renderLists();});service.watchList(`h2hInvites/${service.uid}/items`,value=>{invites=value.filter(v=>v.expiresAt>Date.now());invites.forEach(i=>watchOther(i.code));renderLists();});service.watchList(`h2hRecent/${service.uid}/players`,value=>{recent=value.sort((a,b)=>b.playedAt-a.playedAt);recent.forEach(p=>watchOther(p.code));renderLists();});
 for(const person of people)service.listen(service.fs.doc(service.db,'h2hPresence',person.uid),snap=>{const p=snap.data()||{};presence.set(person.uid,p);const label=document.querySelector('[data-presence-uid="'+person.uid+'"]');if(label)label.textContent=p.lastSeen>Date.now()-70000?'Online':'Offline / not recently active';if(p.roomId)watchOther(p.roomId);renderLists();});
 const heartbeat=()=>service.call('h2hPresence',{code:current?.code||null}).catch(()=>{});heartbeat();setInterval(heartbeat,25000);
 const code=new URL(location.href).searchParams.get('room');if(/^LR-\d{6}$/.test(code||''))await openRoom(code,true);
}
function home(){root.hidden=false;root.innerHTML=`<section class="live-hero"><div><span class="eyebrow">PRIVATE ROOMS · REAL OPPONENTS</span><h1>LIVE HEAD<br>TO HEAD</h1><p>Invite a rival, choose your squad, and meet on the pitch. Every join request stays in the host’s hands.</p></div><div class="live-identity"><small>SIGNED IN</small><strong>${e(service.account.profile.username)}</strong></div></section><div class="live-tabs" role="tablist">${[['create','Create Room'],['join','Join Room'],['invites','Invites'],['recent','Recent Players']].map(([key,label])=>`<button class="hub-button" role="tab" data-tab="${key}" aria-selected="${tab===key}">${label}</button>`).join('')}</div><div id="live-content"></div><section class="live-panel" style="margin-top:28px"><h2>Your rooms</h2><div id="room-list"></div></section>`;renderTab();renderLists();}
function renderTab(){document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));const content=$('live-content');if(!content)return;
 if(tab==='create'){content.innerHTML=`<section class="live-panel"><h2>Your room. Your matchday.</h2><form id="create-room" class="live-form"><div class="live-fields"><label>MATCH LENGTH<select name="duration">${MATCH_DURATIONS.map(n=>`<option value="${n}" ${n===6?'selected':''}>${n} ${n===1?'Minute':'Minutes'}</option>`).join('')}</select></label><label>AI TEAMMATES &amp; GOALKEEPERS<select name="difficulty">${['easy','normal','hard','insane'].map(n=>`<option value="${n}" ${n==='normal'?'selected':''}>${n.toUpperCase()}</option>`).join('')}</select></label><label>LSL SEASON<select name="season">${league.seasons.map(s=>`<option ${String(s.year)==='2026'?'selected':''}>${s.year}</option>`).join('')}</select></label><label>GRENOBLE FIELD LIGHTING<select name="lighting"><option value="day">Day</option><option value="evening" selected>Evening</option><option value="night">Night</option></select></label></div><p>The difficulty controls computer teammates and goalkeepers equally on both teams. The opponent is another human player.</p><div><button class="hub-button primary">CREATE PRIVATE ROOM ↗</button></div></form></section>`;$('create-room').onsubmit=event=>{event.preventDefault();const form=event.currentTarget;runButton(event.submitter,async()=>{const result=await service.room('create',null,{options:Object.fromEntries(new FormData(form))});await openRoom(result.code);});};}
 if(tab==='join'){content.innerHTML=`<section class="live-panel"><h2>Meet on the pitch</h2><form id="join-room" class="live-form"><label>ROOM ID<input name="code" placeholder="LR-482731" pattern="[Ll][Rr]-[0-9]{6}" maxlength="9" required autocapitalize="characters"></label><p>The host must accept your request before you can enter the lobby.</p><div><button class="hub-button primary">REQUEST TO JOIN</button></div></form></section>`;$('join-room').onsubmit=event=>{event.preventDefault();runButton(event.submitter,()=>openRoom(event.currentTarget?.elements?.code?.value||new FormData($('join-room')).get('code'),true));};}
 if(tab==='invites'||tab==='recent'){content.innerHTML=`<section class="live-panel"><h2>${tab==='invites'?'Your invitations':'Recent opponents'}</h2><div id="social-list"></div></section>`;renderLists();}
}
function renderLists(){if($('room-list'))$('room-list').innerHTML=rooms.filter(r=>r.expiresAt>Date.now()).sort((a,b)=>b.updatedAt-a.updatedAt).map(roomCard).join('')||'<p>No active rooms yet. Create one to get started.</p>';const social=$('social-list');if(!social)return;
 if(tab==='invites')social.innerHTML=invites.map(i=>{const r=roomCache.get(i.code);return `<article class="live-room"><div>${status(r)}<h3>${e(i.fromName)} invited you to a Live H2H match</h3><small>${e(i.code)}</small></div><div class="live-actions"><button class="hub-button primary" data-invite="${e(i.code)}" ${r?.status==='OPEN'?'':'disabled'}>JOIN</button><button class="hub-button" data-decline="${e(i.code)}">DECLINE</button></div></article>`;}).join('')||'<p>You’re all caught up. New invitations appear here automatically.</p>';
 if(tab==='recent')social.innerHTML=recent.map(p=>`<article class="live-room"><div><h3>${e(p.username)}</h3>${status(roomCache.get(p.code))}<p>Last played ${new Date(p.playedAt).toLocaleDateString()}</p></div><a class="hub-button" href="./account.html?user=${encodeURIComponent(p.uid)}">PROFILE</a></article>`).join('')||'<p>Your opponents appear here after a completed, verified match.</p>';
}
const runButton=(button,fn)=>busyAction(button,fn,error=>toast(error.message));
async function openRoom(code,request=false){code=String(code).trim().toUpperCase();if(request&&!rooms.some(r=>r.code===code&&r.members.includes(service.uid)))await service.room('request',code);roomStop?.();current=null;renderKey='';roomStop=service.watchRoom(code,room=>{if(!room){toast('Room no longer exists.');return;}current=room;roomCache.set(code,room);renderRoom();connectRoom().catch(error=>toast(error.message));});}
function playerSide(uid){const r=current,choice=r.choices[uid],team=league.get(r.options.season).find(t=>t.id===choice?.team),mine=uid===service.uid,other=uid===r.host?r.guest:r.host,slots=presetSlots(choice?.formation||'2-2-2');return `<section class="live-panel"><span class="eyebrow">${uid===r.host?'HOST':'GUEST'} ${mine?'· YOU':''}</span><h2>${e(r.names[uid])}</h2>${mine&&['OPEN','LOCKED','FULL'].includes(r.status)?`<div class="live-form"><label>TEAM<select id="lobby-team"><option value="">Choose a team</option>${league.get(r.options.season).map(t=>`<option value="${e(t.id)}" ${choice?.team===t.id?'selected':''} ${r.choices[other]?.team===t.id?'disabled':''}>${e(t.name)}</option>`).join('')}</select></label><label>FORMATION<select id="lobby-formation">${FORMATION_ORDER.map(f=>`<option ${choice?.formation===f?'selected':''}>${f}</option>`).join('')}</select></label></div>`:''}${team?`<div class="live-team"><img src="${e(team.logo)}" alt=""><div><strong>${e(team.name)}</strong><small>${e(choice.formation)} · ${r.options.season}</small></div></div><ul class="live-lineup">${choice.lineup.map((id,i)=>{const player=team.roster.find(p=>p.id===id);return `<li><b>${slots[i].role}</b>${mine&&['OPEN','LOCKED','FULL'].includes(r.status)?`<select data-lineup-slot="${i}" aria-label="${slots[i].role} slot ${i+1}">${team.roster.map(p=>`<option value="${e(p.id)}" ${p.id===id?'selected':''}>${e(playerLabel(p))}</option>`).join('')}</select>`:e(playerLabel(player))}</li>`;}).join('')}</ul>`:'<p>Choosing the starting seven…</p>'}<span class="live-ready" data-ready-state="${r.ready[uid]?'ready':'waiting'}">${r.ready[uid]?'✓ READY':'NOT READY'}</span>${mine&&r.status==='FULL'?`<div class="live-actions"><button class="hub-button primary" data-ready="${!r.ready[uid]}" ${choice?'':'disabled'}>${r.ready[uid]?'NOT READY':'READY'}</button></div>`:''}</section>`;}
function renderRoom(){
 const r=current,member=r.members.includes(service.uid);if(r.status!=='OPEN'&&$('join-dialog').open){$('join-dialog').close();popupId=null;}if(!member){const req=r.requests[service.uid];root.innerHTML=`<section class="live-hero"><div><span class="eyebrow">${e(r.code)} · ${e(r.status)}</span><h1>${req?.status==='declined'?'REQUEST DECLINED':'WAITING FOR APPROVAL'}</h1><p>${req?.status==='declined'?'The host declined your request. You can return home and join another room.':r.status==='OPEN'?e(r.names[r.host])+' will accept or deny your request.':'This room is '+e(r.status.toLowerCase())+' and cannot accept you now.'}</p><button class="hub-button" data-home>BACK TO H2H HOME</button></div></section>`;return;}
 if(r.status==='FULL TIME'&&arena){arena.resultStatus=r.verified?'Verified · Saved to both players’ History':r.endReason||'Match ended.';peer?.close();peer=null;connectionEpoch=-1;reconnecting=0;if(!r.verified){arena.stop();arena=null;finishing=false;}else return;}
 if(arena&&activeStates.includes(r.status)){arena.room=r;return;}
 const key=JSON.stringify([r.status,r.choices,r.ready,r.members,r.requests,r.score]);if(key===renderKey)return;renderKey=key;
 root.innerHTML=`<section class="live-hero"><div><span class="eyebrow">${e(r.options.season)} LSL · ${r.options.duration} MIN · AI ${r.options.difficulty.toUpperCase()}</span><h1>${e(r.code)}</h1>${status(r)}<p>HOST: ${e(r.names[r.host])}${r.guest?'':' · WAITING FOR PLAYER…'}</p></div><div class="live-actions"><button class="hub-button" data-copy>COPY ROOM ID</button><button class="hub-button" data-home>H2H HOME</button></div></section>${r.status==='FULL TIME'?`<section class="live-panel"><h2>FULL TIME · ${r.score.join(' – ')}</h2><p>${e(r.endReason||'Verified final result')}</p><a class="hub-button primary" href="./history.html">MATCH HISTORY</a></section>`:`<div class="live-versus">${playerSide(r.host)}<div class="versus">VS</div>${r.guest?playerSide(r.guest):'<section class="live-panel"><h2>Your next rival?</h2><p>Share your Room ID or send an invitation. You decide who enters.</p></section>'}</div><div class="live-actions">${r.host===service.uid&&['OPEN','LOCKED'].includes(r.status)?`<button class="hub-button" data-lock="${r.status==='OPEN'?'lock':'unlock'}">${r.status==='OPEN'?'LOCK ROOM':'UNLOCK ROOM'}</button>`:''}${r.host===service.uid&&r.status==='FULL'?`<button class="hub-button primary" data-start ${r.members.every(id=>r.ready[id])?'':'disabled'}>START MATCH ↗</button>`:''}${activeStates.includes(r.status)?'<button class="hub-button" data-retry>RETRY CONNECTION</button>':'<button class="hub-button" data-leave>LEAVE ROOM</button>'}</div>${r.host===service.uid&&r.status==='OPEN'?`<section class="live-panel" style="margin-top:28px"><h2>Invite a player</h2>${Object.values(r.requests).filter(q=>q.status==='pending'&&Date.now()-q.at<300000).map(q=>`<article class="live-room"><div><strong>${e(q.name)}</strong><p>Waiting for your approval</p></div><button class="hub-button primary" data-review="${e(q.uid)}">REVIEW REQUEST</button></article>`).join('')}<div>${people.map(p=>{const live=presence.get(p.uid);return `<article class="live-room"><div><h3>${e(p.username)}</h3><small data-presence-uid="${e(p.uid)}">${live?.lastSeen>Date.now()-70000?'Online':'Offline / not recently active'}</small>${live?.roomId?status(roomCache.get(live.roomId)):''}</div><button class="hub-button" data-send-invite="${e(p.username)}">INVITE</button></article>`;}).join('')||'<p>No other accounts yet.</p>'}</div></section>`:''}`}`;
 if(r.host===service.uid&&r.status==='OPEN'){const request=Object.values(r.requests).find(q=>q.status==='pending'&&Date.now()-q.at<300000);if(request&&!deferredRequests.has(request.uid+':'+request.at)&&!$('join-dialog').open){popupId=request.uid;$('join-title').textContent=request.name+' wants to join your room';$('join-dialog').showModal();}}
}
async function connectRoom(){
 const r=current;if(!r||!r.members.includes(service.uid)||!activeStates.includes(r.status))return;
 if(connectionEpoch===r.epoch)return;connectionEpoch=r.epoch;peer?.close();
 const side=r.host===service.uid?0:1;
 if(!arena&&side===0&&r.status!=='STARTING'){await service.room('disconnect',r.code);toast('The hosting tab was closed. This match cannot resume; leave it and create a new room.');await service.room('abandon',r.code);return;}
 if(!arena){const teams=r.members.map(id=>buildSquad(league.get(r.options.season).find(t=>t.id===r.choices[id].team),r.choices[id]));arena=new LiveArena({room:r,teams,side,send:(m,fast)=>peer?.send(m,fast),onFinish:finish,onCommand:action=>action==='retry'?task(async()=>{if(service.uid===current.host)await service.room('reconnect',current.code);else{connectionEpoch=-1;await connectRoom();}}):task(()=>service.room(action,r.code)),onError:error=>toast(error.message)});await arena.start();}
 peer=new LivePeer(service,r,{onMessage:m=>arena?.receive(m),onState:(state,reason)=>{
  if(state==='connected'){reconnecting=0;arena?.connection(true);task(()=>service.room('connected',r.code));}
  if(state==='disconnected'||state==='error'){arena?.connection(false,reason||'Opponent disconnected — attempting to reconnect…');if(!reconnecting){reconnecting=Date.now();task(()=>service.room('disconnect',r.code));}}
 }});
 try{await peer.connect();}catch(error){connectionEpoch=-1;arena.connection(false,error.message);if(!reconnecting){reconnecting=Date.now();await service.room('disconnect',r.code).catch(()=>{});}throw error;}
}
async function finish(trace,tick){
 if(finishing)return;finishing=true;const finishedArena=arena;
 try{
  const code=current.code,digest=await traceDigest(trace);
  if(service.uid===current.host){for(let i=0;i<trace.length;i+=300){finishedArena.resultStatus=`Saving match inputs · ${Math.round(i/Math.max(1,trace.length)*100)}%`;await service.call('h2hTrace',{action:'chunk',code,index:i/300,events:trace.slice(i,i+300)});}}
  await service.call('h2hTrace',{action:'confirm',code,digest,tick});finishedArena.resultStatus='Waiting for both confirmations · verifying the match…';
  for(let i=0;i<8;i++){try{await service.call('h2hFinalize',{code});finishedArena.resultStatus='Verified · Saved to both players’ History';return;}catch(error){if(error.code!=='functions/failed-precondition')throw error;await new Promise(resolve=>setTimeout(resolve,3000));}}
  throw Error('Still waiting for the other player. Keep this page open and use Retry Save.');
 }catch(error){finishedArena.resultStatus=error.message;toast(error.message);finishedArena.retrySave=()=>{finishedArena.retrySave=null;finishing=false;finish(trace,tick);};finishedArena.overlayKey=null;}
}
root.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;
 if(b.dataset.tab){tab=b.dataset.tab;renderTab();return;}
 if(b.hasAttribute('data-home')){if(arena)return;roomStop?.();roomStop=null;current=null;home();return;}
 if(b.dataset.room)return runButton(b,()=>openRoom(b.dataset.room));
 if(b.dataset.invite)return runButton(b,()=>openRoom(b.dataset.invite,true));
 if(b.dataset.decline)return runButton(b,()=>service.call('h2hInvite',{action:'decline',code:b.dataset.decline}));
 if(!current)return;
 if(b.hasAttribute('data-copy'))return runButton(b,()=>copyRoomCode(current.code,toast));
 if(b.dataset.review){const q=current.requests[b.dataset.review];if(q){deferredRequests.delete(q.uid+':'+q.at);renderKey='';renderRoom();}return;}
 if(b.dataset.lock)return runButton(b,()=>service.room(b.dataset.lock,current.code));
 if(b.hasAttribute('data-start'))return runButton(b,()=>service.room('start',current.code));
 if(b.hasAttribute('data-ready'))return runButton(b,()=>service.room('ready',current.code,{ready:b.dataset.ready==='true'}));
 if(b.dataset.sendInvite)return runButton(b,async()=>{await service.call('h2hInvite',{code:current.code,username:b.dataset.sendInvite});toast('Invitation sent');});
 if(b.hasAttribute('data-leave'))return runButton(b,async()=>{if(!await confirmAction('Leave this room?',current.host===service.uid?'Your room will close for everyone.':'Your place in the lobby will become available.','LEAVE ROOM'))return;await service.room('leave',current.code);roomStop?.();roomStop=null;current=null;home();});
 if(b.hasAttribute('data-retry')){connectionEpoch=-1;return task(connectRoom);}
});
async function saveChoice(action){root.setAttribute('aria-busy','true');root.querySelectorAll('select').forEach(el=>el.disabled=true);await task(action);root.removeAttribute('aria-busy');renderKey='';if(current)renderRoom();}
root.addEventListener('change',event=>{if(!current)return;const input=event.target,choice=current.choices[service.uid];
 if(input.id==='lobby-team'||input.id==='lobby-formation'){const team=$('lobby-team').value;if(team)saveChoice(()=>service.room('choose',current.code,{team,formation:$('lobby-formation').value,...(team===choice?.team?{lineup:choice.lineup}:{})}));}
 if(input.dataset.lineupSlot!==undefined&&choice){const lineup=[...choice.lineup],slot=Number(input.dataset.lineupSlot),other=lineup.indexOf(input.value);if(other>=0)lineup[other]=lineup[slot];lineup[slot]=input.value;saveChoice(()=>service.room('choose',current.code,{...choice,lineup}));}
});
for(const [id,action]of [['join-accept','accept'],['join-deny','deny']])$(id).onclick=()=>runButton($(id),async()=>{await service.room(action,current.code,{uid:popupId});$('join-dialog').close();popupId=null;renderKey='';renderRoom();});
function deferRequest(){if(current&&popupId){const q=current.requests[popupId];if(q)deferredRequests.add(q.uid+':'+q.at);}popupId=null;$('join-dialog').close();}
$('join-later').onclick=deferRequest;$('join-dialog').addEventListener('cancel',event=>{event.preventDefault();deferRequest();});
setInterval(()=>{if(!current||!current.members.includes(service.uid))return;service.room('heartbeat',current.code).catch(()=>{});if(arena&&reconnecting){const seconds=Math.ceil((25000-(Date.now()-reconnecting))/1000);arena.status='Opponent disconnected — attempting to reconnect… '+Math.max(0,seconds)+'s';if(seconds<=0){task(()=>service.room('timeout',current.code));reconnecting=0;}else if(service.uid===current.host&&Date.now()-reconnecting>4500)task(()=>service.room('reconnect',current.code));}},5000);
setInterval(()=>{if(arena?.host&&arena.ready&&!arena.done&&arena.match.elapsed>0&&current?.kickoffAt&&Date.now()>=current.startedAt)service.call('h2hProgress',{code:current.code,elapsed:arena.match.elapsed,score:arena.match.stats.map(s=>s.goals)}).catch(error=>toast(error.message));},2500);
root.addEventListener('keydown',event=>{const button=event.target.closest('[data-tab]');if(!button||!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const tabs=[...root.querySelectorAll('[data-tab]')],index=tabs.indexOf(button),next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].click();tabs[next].focus();});
Promise.race([Promise.all([service.init(),league.load()]),new Promise((_,reject)=>setTimeout(()=>reject(Error('The connection is taking too long. Check your connection and try again.')),15000))]).then(()=>service.uid?enter():gate()).catch(error=>{root.innerHTML=`<section class="live-hero"><div><span class="eyebrow">PRIVATE ROOMS · REAL OPPONENTS</span><h1>LIVE HEAD<br>TO HEAD</h1><p>Your next matchday starts here.</p></div></section><section class="live-panel live-service-panel"><span class="live-status">CONNECTION UNAVAILABLE</span><h2>Online play is not ready yet</h2><p>${e(error.message)}</p><div class="live-actions"><button class="hub-button primary" id="live-reload">TRY AGAIN</button><a class="hub-button" href="./index.html">BACK TO GAME</a></div><details><summary>Setup information</summary><p>Online rooms use the free Worker backend and Firebase Spark. No paid relay is used.</p><a class="hub-button" href="./LIVE-H2H-SETUP.md">OPEN SETUP GUIDE</a></details></section>`;$('live-reload').onclick=()=>location.reload();});
