import {CloudAccount} from './cloud-account.js';
import {summarize,recordsFor,filterMatches,DIFFICULTY_LABELS} from './match-history.js';
import {navigation,esc,date,modes,difficulties,summaryCards,recordGrid,matchCard,trendChart} from './history-view.js';
const root=document.querySelector('#account-app'),service=new CloudAccount(),requested=new URLSearchParams(location.search).get('user');let profile=null,mode='all',difficulty='all',warning='';
function render(){
  if(!profile){root.innerHTML=navigation('account')+`<main class="hub-main"><div class="hub-heading"><span class="eyebrow">YOUR PLACE IN THE LEAGUE</span><h1>ACCOUNT</h1><p>Create an account to save your matches, collect trophies and climb the charts.</p></div>${warning?`<p class="hub-notice">${esc(warning)}</p>`:''}<a class="hub-button primary" href="./index.html#account">CREATE ACCOUNT / SIGN IN</a></main>`;return;}
  const own=service.user?.uid===profile.uid,history=filterMatches(profile.history,{mode,difficulty,sort:'oldest'}),stats=summarize(history),records=Object.fromEntries(Object.entries(recordsFor(history)).map(([k,v])=>[k,{...v,holder:profile.username,uid:profile.uid,modeLabel:DIFFICULTY_LABELS[difficulty]}]));
  root.innerHTML=navigation('account')+`<main class="hub-main"><section class="profile-hero"><img src="${esc(profile.avatarDataUrl||'./assets/lsl-logo.png')}" alt="Profile picture"><div><span class="eyebrow">LANTERN RUSH PLAYER PROFILE</span><h1>${esc(profile.username)}</h1><p>Member since ${esc(date(profile.createdAtMs))}</p></div>${own?'<button class="hub-button" id="signout">SIGN OUT</button>':''}</section>${warning?`<p class="hub-notice">${esc(warning)}</p>`:''}${own?'<div class="profile-actions"><label class="hub-button">CHANGE PHOTO<input type="file" id="avatar" accept="image/*" hidden></label><a class="hub-button" href="./history.html">FULL HISTORY ↗</a><a class="hub-button" href="./admin.html">ADMIN</a><span id="avatar-status" role="status"></span></div>':''}<div class="charts-toolbar"><label>Game mode<select id="account-mode">${modes(mode)}</select></label><label>CPU difficulty<select id="account-difficulty">${difficulties(difficulty)}</select></label><span>Stats, records and reports follow both filters</span></div>${summaryCards(stats)}<section class="hub-panel"><h2>On the pitch</h2><div class="profile-stat-grid">${[['Assists','assists'],['Shots','shots'],['On target','shotsOnTarget'],['Saves','saves'],['Clean sheets','cleanSheets'],['Passes','passes'],['Fouls','fouls'],['Cards','cards']].map(([label,key])=>`<article class="profile-stat"><span>${label}</span><strong>${stats[key]||0}</strong></article>`).join('')}</div></section>${trendChart(history)}<section class="hub-panel" id="trophies"><h2>Trophy cabinet</h2><div class="trophy-grid">${profile.trophies?.length?profile.trophies.map(t=>`<article class="trophy-card"><span aria-hidden="true">🏆</span><div><strong>${esc(t.title)}</strong><small>${esc(t.description)}</small>${t.earnedAt?`<small>${esc(date(t.earnedAt))}</small>`:''}</div></article>`).join(''):'<p>Complete matches and reach milestones to earn trophies.</p>'}</div></section><section class="hub-panel" id="records"><h2>Personal records</h2>${recordGrid(records)}</section><section class="hub-panel" id="history"><div class="section-head"><h2>Recent match reports</h2>${own?'<a href="./history.html">FULL HISTORY ↗</a>':''}</div><div class="history-list">${[...history].reverse().slice(0,10).map(matchCard).join('')||'<p>No completed reports match these filters. Older reports without a saved difficulty remain under All difficulties.</p>'}</div></section></main>`;
  root.querySelector('#account-mode').onchange=e=>{mode=e.target.value;render();};root.querySelector('#account-difficulty').onchange=e=>{difficulty=e.target.value;render();};root.querySelector('#signout')?.addEventListener('click',async()=>{await service.logout();profile=null;render();});root.querySelector('#avatar')?.addEventListener('change',async e=>{const status=root.querySelector('#avatar-status');status.textContent='Saving photo…';try{profile.avatarDataUrl=await service.updateAvatar(e.target.files[0]);render();}catch(error){status.textContent=error.message;}});
}
root.innerHTML=navigation('account')+'<main class="hub-main"><p role="status">Loading player profile…</p></main>';
service.ready.then(async()=>{try{const raw=requested?await service.getProfile(requested):service.profile;if(raw){try{profile=await service.withHistory(raw);if(profile.archiveIncomplete)warning='Cloud archive unavailable. Showing retained reports only. Publish updated Firestore rules or retry your connection.';else if(profile.legacyMissing)warning=`${profile.legacyMissing} older matches have totals only. Details below use retained reports.`;}catch{profile={...raw,history:raw.history||[]};warning='Cloud archive unavailable. Showing legacy reports only. Check your connection and the updated Firestore rules.';}}else if(requested)warning='This account was not found.';render();}catch{warning='Account could not be loaded. Please retry.';render();}});
