import {CloudAccount,MODE_LABELS} from './cloud-account.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const n=value=>Number(value)||0;
const date=value=>value?new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—';
const modeKeys=Object.keys(MODE_LABELS);
const service=new CloudAccount();
const root=document.getElementById('account-app');
const requestedUid=new URLSearchParams(location.search).get('user');
let profile=null,selectedMode='all',own=false;
const trophyList=[['first-match','FIRST MATCH','Complete your first match.'],['first-win','FIRST WIN','Win a match.'],['hot-streak','HOT STREAK','Win three matches in a row.'],['clean-sheet','SHUTOUT','Win without conceding.'],['rivalry-win','RIVALRY NIGHT','Win a featured rivalry match.'],['tournament-win','TOURNAMENT RUN','Win an Inter-Madrasah fixture.'],['season-win','SEASON CAMPAIGN','Win a season fixture.'],['dream-win','DREAM BUILDER','Win a Dream F.C. CPU match.']];
function statSet(){return profile?.modes?.[selectedMode]||profile?.stats||{};}
function statCards(){const stats=statSet();return [['MATCHES','matches'],['GOALS','goals'],['SHOTS','shots'],['SAVES','saves'],['WINS','wins'],['LOSSES','losses'],['TIES','ties'],['PASS ACCURACY',null]].map(([label,key])=>{const value=key?n(stats[key]):stats.passes?`${Math.round(n(stats.completedPasses)/n(stats.passes)*100)}%`:'—';return `<article class="profile-stat"><span>${label}</span><strong>${value}</strong></article>`;}).join('');}
function recordCards(){const r=profile.records||{};return [['FASTEST OPENING GOAL',r.fastestOpeningGoal?`${Math.floor(n(r.fastestOpeningGoal.seconds)/60)}:${String(Math.floor(n(r.fastestOpeningGoal.seconds)%60)).padStart(2,'0')} · ${r.fastestOpeningGoal.name}`:'—'],['FASTEST HAT-TRICK',r.fastestHattrick?`${Math.floor(n(r.fastestHattrick.seconds)/60)}:${String(Math.floor(n(r.fastestHattrick.seconds)%60)).padStart(2,'0')} · ${r.fastestHattrick.name}`:'—'],['FASTEST 5-GOAL COMEBACK',r.fastestFiveGoalComeback?`${r.fastestFiveGoalComeback.score} · ${r.fastestFiveGoalComeback.teams?.join(' vs ')||'LSL match'}`:'—'],['MOST GOALS IN A GAME',r.mostGoalsGame?`${r.mostGoalsGame.goals} · ${r.mostGoalsGame.name}`:'—'],['BIGGEST WIN',r.biggestWin?`${r.biggestWin.score} · ${r.biggestWin.team}`:'—'],['LONGEST WINNING STREAK',`${n(r.longestWinningStreak)} matches`]].map(([label,value])=>`<article class="record-card"><small>${label}</small><strong>${esc(value)}</strong></article>`).join('');}
function trophyCards(){const earned=new Set((profile.trophies||[]).map(item=>item.id));return trophyList.map(([id,title,description])=>`<article class="trophy-card ${earned.has(id)?'earned':'locked'}"><span>${earned.has(id)?'✦':'○'}</span><div><strong>${title}</strong><small>${description}</small></div><b>${earned.has(id)?'EARNED':'LOCKED'}</b></article>`).join('');}function historyMarkup(){if(!profile.history?.length)return '<p class="account-lede">No matches recorded yet. Complete a match to start your history.</p>';return profile.history.map(match=>`<details class="history-match"><summary><span><strong>${esc(match.teams?.join(' vs ')||'LSL Match')}</strong><small>${esc(match.modeLabel||MODE_LABELS[match.mode]||'Match')} · ${esc(match.season||'')} · ${date(match.date)}</small></span><b>${n(match.score?.[0])} — ${n(match.score?.[1])}</b></summary><div class="history-detail"><div class="history-stat-grid"><span><small>SHOTS</small><b>${n(match.stats?.user?.shots)} — ${n(match.stats?.cpu?.shots)}</b></span><span><small>ON TARGET</small><b>${n(match.stats?.user?.onTarget)} — ${n(match.stats?.cpu?.onTarget)}</b></span><span><small>PASSES</small><b>${n(match.stats?.user?.passes)} — ${n(match.stats?.cpu?.passes)}</b></span><span><small>POSSESSION</small><b>${Math.round(n(match.stats?.user?.possession))} — ${Math.round(n(match.stats?.cpu?.possession))}</b></span><span><small>FOULS</small><b>${n(match.stats?.user?.fouls)} — ${n(match.stats?.cpu?.fouls)}</b></span><span><small>SAVES</small><b>${n(match.stats?.user?.saves)} — ${n(match.stats?.cpu?.saves)}</b></span></div><div class="history-goals">${match.goals?.length?match.goals.map(goal=>`<span>⚽ ${esc(goal.name)}${goal.jersey!=null?' #'+esc(goal.jersey):''} · ${Math.floor(n(goal.time)/60)}:${String(Math.floor(n(goal.time)%60)).padStart(2,'0')}</span>`).join(''):'<span>No goals recorded</span>'}</div></div></details>`).join('');}
function render(){
  if(!profile){root.innerHTML=`<header class="account-top"><a href="./index.html" class="back">← LANTERN RUSH</a><div class="account-top-actions"><a href="./charts.html">CHARTS</a><a href="./admin.html">ADMIN</a></div></header><main class="account-main"><span class="eyebrow">CROSS-DEVICE PROGRESS</span><h1>ACCOUNT</h1><p class="account-lede">Create your Lantern Rush account to play every mode, save your match history, claim records and appear on the charts.</p><div class="account-empty-actions"><a href="./index.html#account" class="primary">CREATE / SIGN IN ↗</a><a href="./charts.html" class="secondary">VIEW CHARTS</a></div></main>`;return;}
  const stats=statSet();root.innerHTML=`<header class="account-top"><a href="./index.html" class="back">← LANTERN RUSH</a><div class="account-top-actions"><a href="./charts.html">CHARTS</a><a href="./admin.html">ADMIN</a>${own?'<button id="account-signout-page">SIGN OUT</button>':''}</div></header><main class="account-main account-profile-page"><section class="profile-hero"><img src="${esc(profile.avatarDataUrl||'./assets/lsl-logo.png')}" alt="${esc(profile.username)} profile picture"><div><span class="eyebrow">LANTERN RUSH PLAYER PROFILE</span><h1>${esc(profile.username)}</h1><p>Member since ${date(profile.createdAtMs)} · ${n(profile.stats.matches)} total matches</p></div></section><div class="profile-mode-toolbar"><label>STATS MODE<select id="profile-mode">${modeKeys.map(key=>`<option value="${key}" ${key===selectedMode?'selected':''}>${esc(MODE_LABELS[key])}</option>`).join('')}</select></label><strong>${esc(MODE_LABELS[selectedMode])}</strong></div><section class="account-section"><div class="section-head"><div><span class="eyebrow">MATCHDAY TOTALS</span><h2>PLAYER STATS</h2></div><b>${n(stats.wins)}W · ${n(stats.losses)}L · ${n(stats.ties)}T</b></div><div class="profile-stat-grid">${statCards()}</div></section><section id="trophies" class="account-section"><div class="section-head"><div><span class="eyebrow">COLLECTED HONOURS</span><h2>TROPHIES</h2></div><b>${(profile.trophies||[]).length}/${trophyList.length}</b></div><div class="trophy-grid">${trophyCards()}</div></section><section id="records" class="account-section"><div class="section-head"><div><span class="eyebrow">ALL-TIME MARKS</span><h2>RECORDS</h2></div></div><div class="record-grid">${recordCards()}</div></section><section id="history" class="account-section"><div class="section-head"><div><span class="eyebrow">EVERY MATCH</span><h2>MATCH HISTORY</h2></div><b>${profile.history?.length||0} SAVED</b></div><div class="history-list">${historyMarkup()}</div></section></main>`;
  root.querySelector('#profile-mode')?.addEventListener('change',event=>{selectedMode=event.target.value;render();});root.querySelector('#account-signout-page')?.addEventListener('click',async()=>{await service.logout();profile=null;own=false;render();});
}
service.ready.then(async()=>{try{profile=requestedUid?await service.getProfile(requestedUid):service.profile;own=!requestedUid||Boolean(profile&&service.user?.uid===profile.uid);render();}catch(error){root.innerHTML=`<main class="account-main"><h1>ACCOUNT</h1><p class="account-lede">Account data could not be loaded: ${esc(error.message)}</p></main>`;}});

