import {mergeAccountProfiles} from './account-store.js';
import {CloudAccount,validateCredentials} from './cloud-account.js';

const root=document.getElementById('admin-app');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const n=value=>Number(value)||0;
const service=new CloudAccount();
let profiles=[],selectedUid='',message='',messageError=false;

function setMessage(value,error=false){message=value;messageError=error;const node=root.querySelector('.admin-message');if(node){node.textContent=value;node.classList.toggle('error',error);}}
function date(value){return value?new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—';}
function signedOut(){root.innerHTML=`<section class="admin-lock"><span class="eyebrow">RESTRICTED CONSOLE</span><h1>ADMIN ACCESS</h1><p>Manage Lantern Rush usernames, passcodes, profiles and match history.</p><form id="admin-login" class="admin-form"><label>ADMIN PASSWORD<input id="admin-password" type="password" inputmode="text" autocomplete="current-password" maxlength="32" required></label><button type="submit">UNLOCK ADMIN</button><p class="admin-message ${messageError?'error':''}">${esc(message)}</p></form><div class="admin-note">Admin access is checked by the online service. No player sign-in is required. Lock the console when finished.</div></section>`;root.querySelector('#admin-login').addEventListener('submit',unlock);}
async function unlock(event){event.preventDefault();const button=event.submitter;button.disabled=true;setMessage('Checking admin access…');try{await service.adminLogin(root.querySelector('#admin-password').value);profiles=await service.getProfiles();selectedUid='';message='Admin console ready.';messageError=false;renderConsole();}catch(error){setMessage(error.message||'Admin sign-in failed.',true);button.disabled=false;}}
function profileRow(profile){const stats=profile.stats||{};return `<tr data-profile="${esc(profile.uid)}" class="${profile.uid===selectedUid?'selected':''}"><td><strong>${esc(profile.username)}</strong><small>${esc(profile.uid)}</small></td><td>${n(stats.matches)}</td><td>${n(stats.wins)} / ${n(stats.losses)} / ${n(stats.ties)}</td><td>${n(stats.goals)}</td><td>${date(profile.updatedAtMs)}</td></tr>`;}
function selectedProfile(){return profiles.find(profile=>profile.uid===selectedUid)||null;}
function consoleMarkup(){const profile=selectedProfile();const stats=profile?.stats||{};return `<div class="admin-toolbar"><button id="admin-signout">LOCK ADMIN</button><a href="./ACCOUNT-RULES.md">FIREBASE SETUP GUIDE ↗</a></div><section class="admin-heading"><div><span class="eyebrow">PROFILE OPERATIONS</span><h1>ACCOUNT ADMIN</h1><p>Review profiles, repair account names, merge game history and reset passcodes.</p></div><span class="eyebrow">${profiles.length} PROFILE${profiles.length===1?'':'S'}</span></section><p class="admin-message ${messageError?'error':''}">${esc(message)}</p><div class="admin-grid"><section class="admin-card"><div class="admin-toolbar"><button id="admin-refresh">REFRESH PROFILES</button><button id="admin-clear">CLEAR SELECTION</button></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>ACCOUNT</th><th>MATCHES</th><th>W / L / T</th><th>GOALS</th><th>UPDATED</th></tr></thead><tbody>${profiles.length?profiles.map(profileRow).join(''):'<tr><td colspan="5">No profiles found yet.</td></tr>'}</tbody></table></div>${profile?`<div class="admin-stats"><article><span>MATCHES</span><strong>${n(stats.matches)}</strong></article><article><span>GOALS</span><strong>${n(stats.goals)}</strong></article><article><span>SAVES</span><strong>${n(stats.saves)}</strong></article><article><span>HISTORY</span><strong>${profile.history?.length||0}</strong></article></div>`:''}</section><aside class="admin-card admin-tools"><h2>ACCOUNT TOOLS</h2><p>${profile?`Selected: <strong>${esc(profile.username)}</strong>`:'Select an account from the table first.'}</p><div class="admin-selection">${profile?`UID: ${esc(profile.uid)}<br>Username: ${esc(profile.username)}`:'No account selected.'}</div><label>NEW ACCOUNT NAME<input id="admin-new-name" maxlength="12" minlength="2" placeholder="2–12 characters" ${profile?'':'disabled'}></label><button class="admin-action" id="admin-rename" ${profile?'':'disabled'}>RESET ACCOUNT NAME</button><button class="admin-action" id="admin-reset" ${profile?'':'disabled'}>RESET PASSCODE</button><button class="admin-action" id="admin-merge" ${profile?'':'disabled'}>MERGE INTO ANOTHER ACCOUNT</button><button class="admin-action danger" id="admin-delete" ${profile?'':'disabled'}>DELETE ACCOUNT</button><div class="admin-claim">Username + six-digit passcode · Firestore profiles</div></aside></div>`;}
function renderConsole(){root.innerHTML=consoleMarkup();root.querySelector('#admin-signout')?.addEventListener('click',async()=>{service.adminLogout();profiles=[];selectedUid='';message='';render();});root.querySelector('#admin-refresh')?.addEventListener('click',refresh);root.querySelector('#admin-clear')?.addEventListener('click',()=>{selectedUid='';renderConsole();});root.querySelectorAll('[data-profile]').forEach(row=>row.addEventListener('click',()=>{selectedUid=row.dataset.profile;renderConsole();}));root.querySelector('#admin-rename')?.addEventListener('click',rename);root.querySelector('#admin-reset')?.addEventListener('click',resetPassword);root.querySelector('#admin-merge')?.addEventListener('click',merge);root.querySelector('#admin-delete')?.addEventListener('click',deleteProfile);}
async function refresh(){try{profiles=await service.getProfiles();message=`Loaded ${profiles.length} profile${profiles.length===1?'':'s'}.`;messageError=false;renderConsole();}catch(error){setMessage(error.message,true);}}
async function rename(){const profile=selectedProfile(),input=root.querySelector('#admin-new-name'),name=input?.value.trim()||'';if(!profile)return;if(!/^[A-Za-z0-9_]{2,12}$/.test(name))return setMessage('Use 2–12 letters, numbers or underscores.',true);if(profiles.some(item=>item.uid!==profile.uid&&item.usernameKey===name.toLowerCase()))return setMessage('That account name is already in use.',true);try{await service.adminUpdateProfile(profile.uid,{username:name});message=`Account renamed to ${name}.`;messageError=false;await refresh();}catch(error){setMessage(error.message||'Rename rejected by Firebase rules.',true);}}
async function resetPassword(){
  const profile=selectedProfile();if(!profile)return;
  const pin=window.prompt('Enter a new 6-digit passcode for '+profile.username+':');
  if(pin===null)return;
  try{validateCredentials(profile.username,pin);await service.adminResetPasscode(profile.uid,pin);setMessage('Passcode reset for '+profile.username+'. Sign in with the new code.');}
  catch(error){setMessage(error.message,true);}
}
function chooseMergeTarget(source,choices){return new Promise(resolve=>{
 const dialog=document.createElement('dialog');dialog.className='admin-merge-dialog admin-card admin-tools';
 dialog.innerHTML=`<form method="dialog"><span class="eyebrow">COMBINE ACCOUNTS</span><h2>Merge ${esc(source.username)}</h2><p>Choose the account to keep. Its username and passcode stay the same. Stats and history are combined, and ${esc(source.username)} can no longer sign in.</p><label>ACCOUNT TO KEEP<select name="target" required><option value="">Choose an account</option>${choices.map(p=>`<option value="${esc(p.uid)}">${esc(p.username)} · ${n(p.stats?.matches)} matches · ${esc(p.uid.slice(0,8))}</option>`).join('')}</select></label><div class="admin-toolbar"><button value="cancel" formnovalidate>CANCEL</button><button value="merge">MERGE ACCOUNTS</button></div></form>`;
 dialog.addEventListener('close',()=>{const id=dialog.returnValue==='merge'?new FormData(dialog.querySelector('form')).get('target'):null;dialog.remove();resolve(id);},{once:true});document.body.append(dialog);dialog.showModal();
});}
async function merge(){const source=selectedProfile();if(!source)return;const choices=profiles.filter(item=>item.uid!==source.uid);if(!choices.length)return setMessage('There is no second account to merge into.',true);const id=await chooseMergeTarget(source,choices),target=choices.find(p=>p.uid===id);if(!target)return;
 root.querySelectorAll('button').forEach(b=>b.disabled=true);setMessage('Combining accounts and preserving match history…');
 try{await service.adminMergeProfiles(source.uid,target.uid,mergeAccountProfiles);selectedUid=target.uid;await refresh();setMessage(`Merged ${source.username} into ${target.username}. Use the destination account to sign in.`,false);}catch(error){renderConsole();setMessage(error.message||'The merge could not be completed.',true);}}
async function deleteProfile(){const profile=selectedProfile();if(!profile||!window.confirm(`Delete the account ${profile.username}? This removes its profile and sign-in. It cannot be undone.`))return;try{await service.adminDeleteProfile(profile.uid);selectedUid='';await refresh();setMessage(`Deleted account ${profile.username}.`,false);}catch(error){setMessage(error.message||'Delete rejected by Firebase rules.',true);}}
function render(){if(service.isAdmin())renderConsole();else signedOut();}
service.ready.then(async()=>{if(service.isAdmin())profiles=await service.getProfiles();render();}).catch(error=>{message=error.message;messageError=true;signedOut();});
