import {CloudAccount,validateCredentials} from './cloud-account.js';

const root=document.getElementById('admin-app');
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const n=value=>Number(value)||0;
const service=new CloudAccount();
let profiles=[],selectedUid='',message='',messageError=false;

function setMessage(value,error=false){message=value;messageError=error;const node=root.querySelector('.admin-message');if(node){node.textContent=value;node.classList.toggle('error',error);}}
function date(value){return value?new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'—';}
function signedOut(){root.innerHTML=`<section class="admin-lock"><span class="eyebrow">RESTRICTED CONSOLE</span><h1>ADMIN ACCESS</h1><p>Manage account profiles for Lantern Rush. This console requires the dedicated admin credential and Firebase account service.</p><form id="admin-login" class="admin-form"><label>ADMIN PASSWORD<input id="admin-password" type="password" inputmode="text" autocomplete="current-password" maxlength="32" required></label><button type="submit">UNLOCK ADMIN</button><p class="admin-message ${messageError?'error':''}">${esc(message)}</p></form><div class="admin-note">Admin mutations require a Firebase Authentication custom claim named <strong>admin</strong>. The browser password opens this console, but Firebase rules never trust a password shipped in public JavaScript.</div></section>`;root.querySelector('#admin-login').addEventListener('submit',unlock);}
async function unlock(event){event.preventDefault();const button=event.submitter;button.disabled=true;setMessage('Checking admin access…');try{await service.adminLogin(root.querySelector('#admin-password').value);profiles=await service.getProfiles();selectedUid='';message=service.isAdmin()?'Admin console ready.':'Signed in, but the Firebase admin claim is still missing.';messageError=!service.isAdmin();renderConsole();}catch(error){setMessage(error.message||'Admin sign-in failed.',true);button.disabled=false;}}
function profileRow(profile){const stats=profile.stats||{};return `<tr data-profile="${esc(profile.uid)}" class="${profile.uid===selectedUid?'selected':''}"><td><strong>${esc(profile.username)}</strong><small>${esc(profile.uid)}</small></td><td>${n(stats.matches)}</td><td>${n(stats.wins)} / ${n(stats.losses)} / ${n(stats.ties)}</td><td>${n(stats.goals)}</td><td>${date(profile.updatedAtMs)}</td></tr>`;}
function selectedProfile(){return profiles.find(profile=>profile.uid===selectedUid)||null;}
function consoleMarkup(){const profile=selectedProfile();const stats=profile?.stats||{};return `<header class="admin-top"><a class="admin-brand" href="./index.html"><img src="./assets/lsl-logo.png" alt="LSL"><span>LANTERN RUSH<br>ADMIN CONSOLE</span></a><div class="admin-top-actions"><a href="./account.html">ACCOUNT</a><a href="./charts.html">CHARTS</a><button id="admin-signout">SIGN OUT</button></div></header><section class="admin-heading"><div><span class="eyebrow">PROFILE OPERATIONS</span><h1>ACCOUNT ADMIN</h1><p>Review profiles, repair account names, merge game history and flag password resets.</p></div><span class="eyebrow">${profiles.length} PROFILE${profiles.length===1?'':'S'}</span></section><p class="admin-message ${messageError?'error':''}">${esc(message)}</p><div class="admin-grid"><section class="admin-card"><div class="admin-toolbar"><button id="admin-refresh">REFRESH PROFILES</button><button id="admin-clear">CLEAR SELECTION</button></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>ACCOUNT</th><th>MATCHES</th><th>W / L / T</th><th>GOALS</th><th>UPDATED</th></tr></thead><tbody>${profiles.length?profiles.map(profileRow).join(''):'<tr><td colspan="5">No profiles found yet.</td></tr>'}</tbody></table></div>${profile?`<div class="admin-stats"><article><span>MATCHES</span><strong>${n(stats.matches)}</strong></article><article><span>GOALS</span><strong>${n(stats.goals)}</strong></article><article><span>SAVES</span><strong>${n(stats.saves)}</strong></article><article><span>HISTORY</span><strong>${profile.history?.length||0}</strong></article></div>`:''}</section><aside class="admin-card admin-tools"><h2>ACCOUNT TOOLS</h2><p>${profile?`Selected: <strong>${esc(profile.username)}</strong>`:'Select an account from the table first.'}</p><div class="admin-selection">${profile?`UID: ${esc(profile.uid)}<br>Login address: ${esc(profile.loginEmail||'legacy account')}`:'No account selected.'}</div><label>NEW ACCOUNT NAME<input id="admin-new-name" maxlength="12" minlength="2" placeholder="2–12 characters" ${profile?'':'disabled'}></label><button class="admin-action" id="admin-rename" ${profile?'':'disabled'}>RESET ACCOUNT NAME</button><button class="admin-action" id="admin-reset" ${profile?'':'disabled'}>FLAG PASSWORD RESET</button><button class="admin-action" id="admin-merge" ${profile?'':'disabled'}>MERGE INTO ANOTHER ACCOUNT</button><button class="admin-action danger" id="admin-delete" ${profile?'':'disabled'}>DELETE PROFILE DATA</button><div class="admin-claim">${service.isAdmin()?'Firebase admin claim confirmed.':'Firebase admin claim missing: reads work, but profile mutations will be rejected by Firestore rules.'}</div></aside></div>`;}
function renderConsole(){root.innerHTML=consoleMarkup();root.querySelector('#admin-signout')?.addEventListener('click',async()=>{await service.logout();profiles=[];selectedUid='';message='';render();});root.querySelector('#admin-refresh')?.addEventListener('click',refresh);root.querySelector('#admin-clear')?.addEventListener('click',()=>{selectedUid='';renderConsole();});root.querySelectorAll('[data-profile]').forEach(row=>row.addEventListener('click',()=>{selectedUid=row.dataset.profile;renderConsole();}));root.querySelector('#admin-rename')?.addEventListener('click',rename);root.querySelector('#admin-reset')?.addEventListener('click',resetPassword);root.querySelector('#admin-merge')?.addEventListener('click',merge);root.querySelector('#admin-delete')?.addEventListener('click',deleteProfile);}
async function refresh(){try{profiles=await service.getProfiles();message=`Loaded ${profiles.length} profile${profiles.length===1?'':'s'}.`;messageError=false;renderConsole();}catch(error){setMessage(error.message,true);}}
async function rename(){const profile=selectedProfile(),input=root.querySelector('#admin-new-name'),name=input?.value.trim()||'';if(!profile)return;if(!/^[A-Za-z0-9_]{2,12}$/.test(name))return setMessage('Use 2–12 letters, numbers or underscores.',true);if(profiles.some(item=>item.uid!==profile.uid&&item.usernameKey===name.toLowerCase()))return setMessage('That account name is already in use.',true);try{await service.adminUpdateProfile(profile.uid,{username:name});message=`Account renamed to ${name}.`;messageError=false;await refresh();}catch(error){setMessage(error.message||'Rename rejected by Firebase rules.',true);}}
async function resetPassword(){const profile=selectedProfile();if(!profile)return;try{await service.adminRequestPasswordReset(profile.uid);setMessage(`Password reset flagged for ${profile.username}. A trusted Firebase Admin SDK workflow must complete the actual passcode change.`,false);await refresh();}catch(error){setMessage(error.message||'Password reset request rejected by Firebase rules.',true);}}
function addStats(target,source){for(const key of ['matches','goals','shots','saves','wins','losses','ties','shotsOnTarget','passes','completedPasses','fouls','corners','cleanSheets'])target[key]=n(target[key])+n(source?.[key]);}
function mergedProfile(source,target){const merged=JSON.parse(JSON.stringify(target));merged.stats=merged.stats||{};addStats(merged.stats,source.stats);merged.modes=merged.modes||{};for(const mode of Object.keys(source.modes||{})){merged.modes[mode]??={};addStats(merged.modes[mode],source.modes[mode]);}merged.trophies=[...(merged.trophies||[]),...(source.trophies||[])].filter((item,index,list)=>list.findIndex(other=>other.id===item.id)===index).slice(0,20);merged.history=[...(merged.history||[]),...(source.history||[])].sort((a,b)=>n(b.date)-n(a.date)).slice(0,50);merged.currentStreak=Math.max(n(merged.currentStreak),n(source.currentStreak));merged.records={...(source.records||{}),...(merged.records||{})};return merged;}
async function merge(){const source=selectedProfile();if(!source)return;const choices=profiles.filter(item=>item.uid!==source.uid);if(!choices.length)return setMessage('There is no second account to merge into.',true);const targetName=window.prompt(`Merge ${source.username} into which account? Enter the exact username.`,choices.map(item=>item.username).join(', '));const target=choices.find(item=>item.username.toLowerCase()===String(targetName||'').trim().toLowerCase());if(!target)return setMessage('Merge cancelled: target account was not found.',true);if(!window.confirm(`Merge ${source.username} into ${target.username}? The source profile data will be deleted.`))return;try{const merged=mergedProfile(source,target);await service.adminUpdateProfile(target.uid,{stats:merged.stats,modes:merged.modes,records:merged.records,trophies:merged.trophies,currentStreak:merged.currentStreak,history:merged.history});await service.adminDeleteProfile(source.uid);selectedUid=target.uid;await refresh();setMessage(`Merged ${source.username} into ${target.username}. Firebase Auth source credentials remain until a trusted server removes them.`,false);}catch(error){setMessage(error.message||'Merge rejected by Firebase rules.',true);}}
async function deleteProfile(){const profile=selectedProfile();if(!profile||!window.confirm(`Delete all saved profile data for ${profile.username}?`))return;try{await service.adminDeleteProfile(profile.uid);selectedUid='';await refresh();setMessage(`Deleted profile data for ${profile.username}.`,false);}catch(error){setMessage(error.message||'Delete rejected by Firebase rules.',true);}}
function render(){if(service.isAdmin()||service.user?.email?.endsWith('@accounts.lsl-rivals.app')&&profiles.length)renderConsole();else signedOut();}
service.ready.then(render).catch(error=>{message=error.message;messageError=true;signedOut();});
