import {CloudAccount} from './cloud-account.js';
import {MODE_LABELS,DIFFICULTY_LABELS,RECORDS,filterMatches,recordsFor,summarize} from './match-history.js';
import {navigation,esc,modes,difficulties,recordGrid} from './history-view.js';
const root=document.querySelector('#charts-app'),service=new CloudAccount();let profiles=[],mode='all',difficulty='all',metric='wins',warning='';
const metrics={wins:'Wins',goals:'Goals',assists:'Assists',saves:'Saves',matches:'Matches',shots:'Shots',cleanSheets:'Clean sheets',winPercent:'Win %'};
function render(){
  const list=profiles.map(p=>{const matches=filterMatches(p.history,{mode,difficulty});return {p,matches,stats:summarize(matches)};}).filter(r=>r.matches.length).sort((a,b)=>(b.stats[metric]||0)-(a.stats[metric]||0)||(b.stats.goals||0)-(a.stats.goals||0)),holders={};
  for(const {p,matches}of list){const records=recordsFor(matches);for(const [key,,,lower]of RECORDS){const record=records[key];if(record&&(!holders[key]||(lower?record.value<holders[key].value:record.value>holders[key].value)))holders[key]={...record,holder:p.username,uid:p.uid,modeLabel:MODE_LABELS[mode]+' · '+DIFFICULTY_LABELS[difficulty]};}}
  const value=s=>metric==='winPercent'?(s[metric]||0).toFixed(1)+'%':s[metric]||0,max=Math.max(1,...list.map(r=>r.stats[metric]||0));
  root.innerHTML=navigation('charts')+`<main class="hub-main"><div class="hub-heading"><span class="eyebrow">THE LANTERN RUSH HONOURS BOARD</span><h1>CHARTS</h1><p>Standout accounts. Unforgettable matches. Records built from completed match reports.</p></div>${warning?`<p class="hub-notice" role="status">${esc(warning)}</p>`:''}<div class="charts-toolbar"><label>Game mode<select id="charts-mode">${modes(mode)}</select></label><label>CPU difficulty<select id="charts-difficulty">${difficulties(difficulty)}</select></label><label>Rank by<select id="charts-metric">${Object.entries(metrics).map(([k,v])=>`<option value="${k}" ${metric===k?'selected':''}>${v}</option>`).join('')}</select></label><span>${list.length} account${list.length===1?'':'s'} with recorded matches</span></div>${list.length?`<section class="podium" aria-label="Top accounts">${list.slice(0,3).map(({p,stats},i)=>`<a class="podium-card" href="./account.html?user=${encodeURIComponent(p.uid)}"><span class="podium-place">${i+1}</span><img src="${esc(p.avatarDataUrl||'./assets/lsl-logo.png')}" alt=""><strong>${esc(p.username)}</strong><small>${value(stats)} ${metrics[metric]}</small></a>`).join('')}</section><section class="hub-panel"><h2>${metrics[metric]} leaders</h2><div class="leader-bars">${list.slice(0,10).map(({p,stats})=>`<div><a href="./account.html?user=${encodeURIComponent(p.uid)}">${esc(p.username)}</a><span><i style="width:${(stats[metric]||0)/max*100}%"></i></span><b>${value(stats)}</b></div>`).join('')}</div></section>`:'<section class="hub-panel"><h2>The next record could be yours</h2><p>No completed reports match this mode and difficulty yet.</p><a class="hub-button primary" href="./index.html">PLAY A MATCH</a></section>'}<section class="hub-panel"><h2>Account leaderboard</h2><div class="table-scroll"><table class="chart-table"><thead><tr><th>Rank</th><th>Account</th>${['Matches','Wins','Draws','Losses','Goals','Assists','Shots','On target','Saves','Clean sheets','Fouls','Cards'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${list.map(({p,stats},i)=>`<tr><td>${i+1}</td><th><a href="./account.html?user=${encodeURIComponent(p.uid)}">${esc(p.username)}</a></th>${['matches','wins','ties','losses','goals','assists','shots','shotsOnTarget','saves','cleanSheets','fouls','cards'].map(k=>`<td>${stats[k]||0}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section><section class="hub-panel"><div class="section-head"><h2>Record holders</h2><span>${esc(MODE_LABELS[mode])} · ${esc(DIFFICULTY_LABELS[difficulty])}</span></div><p>The podium, leaderboard and records use the selected mode and difficulty. Matches without a saved difficulty only appear under All difficulties. Match records are team totals. Points = goals + assists. Hat tricks measure the time between an individual scorer’s first and third goals. Corner goals count the same attacking possession within eight seconds of a corner.</p>${recordGrid(holders)}</section></main>`;
  root.querySelector('#charts-mode').onchange=e=>{mode=e.target.value;render();};root.querySelector('#charts-difficulty').onchange=e=>{difficulty=e.target.value;render();};root.querySelector('#charts-metric').onchange=e=>{metric=e.target.value;render();};
}
root.innerHTML=navigation('charts')+'<main class="hub-main"><p role="status">Loading the honours board…</p></main>';
service.ready.then(async()=>{try{const raw=await service.getProfiles();const results=await Promise.allSettled(raw.map(p=>service.withHistory(p)));profiles=results.map((r,i)=>r.status==='fulfilled'?r.value:{...raw[i],history:raw[i].history||[]});if(results.some(r=>r.status==='rejected'||r.value?.archiveIncomplete))warning='Some archives could not be loaded. Showing available legacy reports; records may be incomplete. Check your connection and updated Firestore rules.';else if(profiles.some(p=>p.legacyMissing))warning='Some older reports were not retained. Charts use available reports; missing details are not invented.';render();}catch{warning='Charts could not be loaded. Check your connection and Firestore rules, then reload.';render();}});
