import {escapeHTML as e} from './config.js';
import {teamKit} from './kits.js';
import {playerLabel} from './player-label.js';
import {playerRatings} from './match/attributes.js';

const $=id=>document.getElementById(id);
const STORE='lsl-dream-fc-v1';
const POSITIONS=['GK','DEF','DEF','MID','MID','FWD','FWD'];
const tier=ovr=>ovr>=100?'LEGENDARY':ovr>=98?'ULTIMATE':ovr>=95?'PREMIUM':ovr>=90?'SPECIAL':ovr>=85?'ELITE':ovr>=80?'GOLD':ovr>=70?'SILVER':'BRONZE';
const money=n=>Number(n||0).toLocaleString();
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));

export class DreamMenu{
  constructor(app){
    this.app=app;this.meta=null;this.tab='home';this.reveal=null;this.dragKey='';
    this.root=$('dream-flow');
    this.root?.addEventListener('click',event=>this.click(event));
    this.root?.addEventListener('change',event=>this.change(event));
    this.root?.addEventListener('dragstart',event=>{const card=event.target.closest('[data-dream-card]');if(card){this.dragKey=card.dataset.dreamCard;event.dataTransfer?.setData('text/plain',this.dragKey);}});
    this.root?.addEventListener('dragover',event=>{if(event.target.closest('[data-dream-slot]'))event.preventDefault();});
    this.root?.addEventListener('drop',event=>{const slot=event.target.closest('[data-dream-slot]');if(!slot)return;event.preventDefault();const key=event.dataTransfer?.getData('text/plain')||this.dragKey;if(key)this.assign(key,Number(slot.dataset.dreamSlot));});
  }
  async load(){
    try{const response=await fetch(new URL('../data/ultimate-team.json',import.meta.url),{cache:'no-cache'});this.meta=await response.json();}
    catch{this.meta={packs:[],events:[],objectives:[],rankedDivisions:[]};}
  }
  key(card){return card?.cardKey||card?.key||'';}
  catalog(){
    const cards=[];
    for(const season of this.app.data.seasons||[]){
      for(const team of this.app.data.get(season.year)||[]){
        for(const player of team.roster||[]){
          const overall=Number(player.overall);
          cards.push({cardKey:`${season.year}|${team.id}|${player.id}|base`,baseKey:`${season.year}|${team.id}|${player.id}|base`,season:String(season.year),teamId:team.id,teamName:team.name,teamLogo:team.logo,teamKit:team.kit||team.colors?.primary||'#4aa77d',name:player.name,jersey:player.jersey,position:player.position||'Player',role:player.role||'',overall:Number.isFinite(overall)?overall:null,unrated:!Number.isFinite(overall),program:'base',programName:'BASE MT',source:player});
        }
      }
    }
    return cards;
  }
  get cards(){if(!this._catalog)this._catalog=this.catalog();return this._catalog;}
  card(key){
    if(!key)return null;
    const direct=this.cards.find(card=>card.cardKey===key);if(direct)return direct;
    const special=this.cards.find(card=>card.cardKey===key.split('|').slice(1).join('|'));if(!special)return null;
    const program=key.split('|')[0],definition=(this.meta?.cardPrograms||[]).find(item=>item.id===program),base=special.overall;
    const overall=Number.isFinite(base)?Math.min(100,base+Number(definition?.boost||0)):null;
    return {...special,cardKey:key,program,programName:definition?.name||program.toUpperCase(),overall};
  }
  defaultState(){
    const team=this.app.selected?.user||this.app.data.get(this.app.settings.value.season)?.[0];
    const starters=(team?.lineup||[]).map(p=>`${team.season}|${team.id}|${p.id}|base`),bench=(team?.bench||[]).slice(0,5).map(p=>`${team.season}|${team.id}|${p.id}|base`);
    return {customTeam:{name:'LANTERN DREAM FC',badge:'assets/lsl-logo.png',primary:'#d4af55',secondary:'#113c35',homeKit:'#113c35',awayKit:'#f4f0dc'},collection:[...starters,...bench],squad:starters,subs:bench,coins:5000,vouchers:3000,eventPoints:{},objectives:{},ranked:{rp:0,streak:0,highest:'Bronze III',season:1},locked:[],lastPack:null,unrated:[]};
  }
  read(){
    if(this.state)return this.state;
    let saved=null;try{saved=JSON.parse(localStorage.getItem(STORE)||'null');}catch{}
    this.state=saved&&typeof saved==='object'?{...this.defaultState(),...saved,customTeam:{...this.defaultState().customTeam,...(saved.customTeam||{})},ranked:{...this.defaultState().ranked,...(saved.ranked||{})}}:this.defaultState();
    this.state.collection=Array.isArray(this.state.collection)?this.state.collection:[];this.state.eventPoints??={};this.state.objectives??={};this.state.squad=(this.state.squad||[]).filter(key=>this.card(key));this.state.subs=(this.state.subs||[]).filter(key=>this.card(key));
    if(this.state.squad.length<7){const fallback=this.defaultState();this.state.squad=[...fallback.squad];this.state.subs=[...fallback.subs];this.state.collection=[...this.state.collection,...fallback.collection];}
    return this.state;
  }
  save(){try{localStorage.setItem(STORE,JSON.stringify(this.state));}catch{} }
  prepare(){if(this.app.mode!=='dream')return;this.read();this.tab='home';this.reveal=null;this._catalog=null;const season=String(this.app.settings.value.season);const selected=this.app.data.get(season).find(t=>t.id===this.app.settings.value.userTeam)||this.app.data.get(season)[0];if(selected)this.app.selected.user=selected;}
  rank(){const rp=Number(this.read().ranked.rp||0);const list=this.meta?.rankedDivisions||[];return list.reduce((best,item)=>rp>=item.rp?item:best,list[0]||{name:'Bronze III',rp:0,target:65});}
  teamFromCards(name,keys,kit='#113c35',logo='assets/lsl-logo.png'){
    const cards=keys.map(key=>this.card(key)).filter(Boolean);const source=cards.length?cards:this.cards.filter(card=>Number.isFinite(card.overall)).slice(0,7);
    const lineup=source.slice(0,7).map((card,index)=>({...card.source,id:`dream-${card.cardKey}`,name:card.name,jersey:card.jersey,position:card.position,overall:card.overall,role:POSITIONS[index],slot:index,cardKey:card.cardKey}));
    while(lineup.length<7){const placeholder={id:`dream-placeholder-${lineup.length}`,name:`Player${lineup.length+1}`,position:POSITIONS[lineup.length],role:POSITIONS[lineup.length],slot:lineup.length,overall:null};lineup.push(placeholder);}
    const bench=keys.slice(7).map(key=>this.card(key)).filter(Boolean).map(card=>({...card.source,id:`dream-bench-${card.cardKey}`,name:card.name,jersey:card.jersey,position:card.position,overall:card.overall,role:card.position,cardKey:card.cardKey}));
    const values=lineup.map(player=>Number(player.overall)).filter(Number.isFinite),overall=values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):null;
    return {id:`dream-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,name,shortName:name.slice(0,14),division:'Ultimate Team',season:'LSL',logo,logoFallback:false,kit,uniform:teamKit('',name,kit),colors:{primary:kit},lineup,bench,roster:[...lineup,...bench],overall};
  }
  cpuKeys(target){
    const eligible=this.cards.filter(card=>Number.isFinite(card.overall));if(!eligible.length)return [];
    const sorted=[...eligible].sort((a,b)=>Math.abs((a.overall||0)-target)-Math.abs((b.overall||0)-target));const chosen=[];const usedTeams=new Set();
    for(const card of sorted){if(chosen.length>=7)break;if(card.position?.toLowerCase().includes('goal')&&chosen.some(c=>c.position?.toLowerCase().includes('goal')))continue;chosen.push(card);usedTeams.add(card.teamId);}
    return chosen.map(card=>card.cardKey);
  }
  badgeOptions(){
    const seen=new Set(),items=[];for(const team of Object.values(this.app.data.teams||{}).flat()){if(!team.logo||seen.has(team.logo))continue;seen.add(team.logo);items.push({name:team.name,logo:team.logo});}return items;
  }
  teamMetrics(keys){
    const values=keys.slice(0,7).map(key=>this.card(key)?.overall).map(Number);const avg=items=>{const nums=items.map(key=>Number(this.card(key)?.overall)).filter(Number.isFinite);return nums.length?Math.round(nums.reduce((a,b)=>a+b,0)/nums.length):'—';};return {attack:avg(keys.slice(5,7)),mid:avg(keys.slice(3,5)),defence:avg(keys.slice(1,3)),keeper:avg(keys.slice(0,1)),overall:values.filter(Number.isFinite).length?Math.round(values.filter(Number.isFinite).reduce((a,b)=>a+b,0)/values.filter(Number.isFinite).length):'—'};
  }
  oddsText(value){const pct=Number(value||0)*100;return pct<.1&&pct>0?'<0.1%':(pct%1?pct.toFixed(pct<1?1:0):pct.toFixed(0))+'%';}
  playRanked(eventId='ranked'){
    this.read();this.save();const rank=this.rank(),target=Number(rank.target||75),user=this.teamFromCards(this.state.customTeam.name,this.state.squad,this.state.customTeam.homeKit,this.state.customTeam.badge),cpu=this.teamFromCards('LSL CPU SELECT',this.cpuKeys(target), '#48657a','assets/lsl-logo.png');
    this.app.mode='dream';this.app.selected={user,cpu};this.currentEvent=eventId==='ranked'?null:eventId;this.app.start();
  }
  assign(key,index){
    this.read();if(!this.state.collection.includes(key))return;const old=this.state.squad.indexOf(key);if(old>=0){[this.state.squad[old],this.state.squad[index]]=[this.state.squad[index],this.state.squad[old]];}else{const displaced=this.state.squad[index];this.state.squad[index]=key;this.state.subs=this.state.subs.filter(item=>item!==key);if(displaced&&!this.state.subs.includes(displaced))this.state.subs.unshift(displaced);}this.state.squad=[...new Set(this.state.squad)].slice(0,7);this.save();this.render();}
  openPack(id){
    const pack=(this.meta?.packs||[]).find(item=>item.id===id);if(!pack)return;this.read();const currency=pack.currency==='coins'?'coins':'vouchers';if(pack.currency!=='reward'&&(this.state[currency]||0)<pack.cost){this.flash('NOT ENOUGH '+currency.toUpperCase(),`You need ${money(pack.cost)} ${currency}.`);return;}if(pack.currency!=='reward')this.state[currency]-=pack.cost;
    const min=Number(pack.minimum||60),odds=Object.entries(pack.odds||{}),roll=Math.random();let cursor=0,chosen='';for(const [label,weight] of odds){cursor+=Number(weight)||0;if(roll<=cursor){chosen=label;break;}}const tierMinimum={bronze:60,silver:70,gold:80,elite:85,special:90,premium:95};const threshold=/^(\d+)\+$/.exec(chosen)?.[1]||tierMinimum[chosen]||min;const pool=this.cards.filter(card=>Number.isFinite(card.overall)&&card.overall>=Math.max(min,Number(threshold)));const fallback=this.cards.filter(card=>Number.isFinite(card.overall)&&card.overall>=min);const pick=(pool.length?pool:fallback)[Math.floor(Math.random()*(pool.length?pool:fallback).length)];if(!pick){this.flash('PACK UNAVAILABLE','No rated LSL cards are loaded.');return;}const special=['toty','tots','rivalries','inter-madrasah'].includes(id)&&Math.random()<.35;const key=special?`${id}|${pick.cardKey}`:pick.cardKey;this.state.collection.push(key);this.state.lastPack={pack:id,card:key,at:Date.now()};this.save();this.reveal={pack,card:this.card(key)};this.tab='packs';this.render();}
  flash(title,message){this.reveal={message,title};this.render();setTimeout(()=>{if(this.reveal?.message){this.reveal=null;this.render();}},2400);}
  afterGame(match){
    this.read();const own=match.stats[0],opp=match.stats[1],won=own.goals>opp.goals,draw=own.goals===opp.goals,rank=this.rank(),loss=Number(rank.loss||10);let delta=won?32:draw?8:-loss;const streak=won?Number(this.state.ranked.streak||0)+1:0;delta+=won?(streak>=10?8:streak>=5?5:streak>=3?3:0):0;this.state.ranked.rp=Math.max(0,Number(this.state.ranked.rp||0)+delta);this.state.ranked.streak=streak;this.state.ranked.highest=this.rank().name;this.state.coins+=won?500:draw?250:100;this.state.vouchers+=won?100:draw?50:25;this.state.objectives['daily-match']=Math.min(2,Number(this.state.objectives['daily-match']||0)+1);this.state.objectives['weekly-win']=Math.min(5,Number(this.state.objectives['weekly-win']||0)+(won?1:0));if(this.currentEvent){this.state.eventPoints[this.currentEvent]=Number(this.state.eventPoints[this.currentEvent]||0)+(won?250:100);this.state.objectives['event-match']=Math.min(1,Number(this.state.objectives['event-match']||0)+1);}this.save();this.lastResult={won,draw,delta,score:`${own.goals}–${opp.goals}`};this.tab='home';}
  click(event){
    const tab=event.target.closest('[data-dream-tab]')?.dataset.dreamTab;if(tab){this.tab=tab;this.reveal=null;this.render();return;}
    const ranked=event.target.closest('[data-dream-ranked]');if(ranked){this.playRanked();return;}
    const eventPlay=event.target.closest('[data-dream-event]');if(eventPlay){this.playRanked(eventPlay.dataset.dreamEvent);return;}
    const pack=event.target.closest('[data-dream-open-pack]');if(pack){this.openPack(pack.dataset.dreamOpenPack);return;}
    const slot=event.target.closest('[data-dream-slot]');if(slot){const card=event.target.closest('[data-dream-card]');if(card)this.assign(card.dataset.dreamCard,Number(slot.dataset.dreamSlot));return;}
    const card=event.target.closest('[data-dream-card]');if(card){this.reveal={detail:this.card(card.dataset.dreamCard)};this.render();return;}
    const save=event.target.closest('[data-dream-save]');if(save){this.save();this.flash('SQUAD SAVED','Your LSL Dream F.C. lineup is ready.');return;}
    const lock=event.target.closest('[data-dream-lock]');if(lock){const key=lock.dataset.dreamLock;this.read().locked??=[];this.state.locked=this.state.locked.includes(key)?this.state.locked.filter(item=>item!==key):[...this.state.locked,key];this.save();this.render();return;}
    if(event.target.closest('[data-dream-close-reveal]')){this.reveal=null;this.render();}
  }
  change(event){const input=event.target;if(input.id==='dream-season'){this.app.settings.set('season',input.value);this.app.chooseDefaults();this._catalog=null;this.render();return;}if(input.id==='dream-team-name'){this.read().customTeam.name=input.value.trim().slice(0,26)||'LANTERN DREAM FC';this.save();}if(input.id==='dream-team-badge'){this.read().customTeam.badge=input.value;this.save();this.render();}if(input.dataset.dreamColor){this.read().customTeam[input.dataset.dreamColor]=input.value;this.save();this.render();}}
  cardMarkup(key,active=false){const card=this.card(key);if(!card)return '';const r=playerRatings(card.source||card);return `<button class="dream-card ${active?'is-active':''}" title="SPD ${r.speed} · SHO ${r.shooting} · PAS ${r.passing} · DRI ${r.dribbling} · DEF ${r.defending}" draggable="true" data-dream-card="${e(key)}"><span class="dream-card-ovr">${card.overall??'—'}</span><span class="dream-card-position">${e((card.position||'PLAYER').slice(0,3).toUpperCase())}</span><strong>${e(card.name)}</strong><small>${e(card.teamName)} · #${card.jersey??'—'}</small><em>${e(card.programName||'BASE MT')}</em></button>`;}
  rankMarkup(){const rank=this.rank(),next=(this.meta?.rankedDivisions||[]).find(item=>item.rp>rank.rp),rp=Number(this.read().ranked.rp||0),progress=next?clamp((rp-rank.rp)/(next.rp-rank.rp)*100,0,100):100;return `<div class="dream-rank-card"><span class="eyebrow">RANKED · SEASON 1</span><strong>${e(rank.name)}</strong><span>${money(rp)} / ${next?money(next.rp):'MAX'} RP</span><div class="dream-progress"><i style="width:${progress}%"></i></div><small>${next?money(next.rp-rp)+' RP until '+e(next.name):'LSL ICON STATUS'}</small></div>`;}
  render(){
    if(!this.root||this.app.mode!=='dream')return;this.read();this.root.hidden=false;const s=this.state,rank=this.rank(),owned=s.collection.length,base=this.card(s.squad[0]);
    const content=this.tab==='home'?this.homeMarkup(rank,owned):this.tab==='my-team'?this.teamMarkup():this.tab==='play'||this.tab==='ranked'?this.playMarkup():this.tab==='events'?this.eventsMarkup():this.tab==='packs'?this.packsMarkup():this.tab==='objectives'?this.objectivesMarkup():this.tab==='collection'?this.collectionMarkup():this.inventoryMarkup();
    this.root.innerHTML=`<div class="dream-shell"><header class="dream-header"><div><span class="eyebrow">LANTERN SOCCER LEAGUE</span><h1>LSL <em>DREAM F.C.</em></h1></div><div class="dream-header-tools"><label class="dream-season-picker">SEASON <select id="dream-season">${(this.app.data.seasons||[]).map(item=>`<option value="${e(item.year)}" ${String(item.year)===String(this.app.settings.value.season)?'selected':''}>${e(item.year)}</option>`).join('')}</select></label><div class="dream-wallet"><span>🪙 ${money(s.coins)}</span><span>🎟 ${money(s.vouchers)}</span></div></div></header><nav class="dream-nav" aria-label="Ultimate Team"><button data-dream-tab="home" class="${this.tab==='home'?'active':''}">HOME</button><button data-dream-tab="my-team" class="${this.tab==='my-team'?'active':''}">MY TEAM</button><button data-dream-tab="play" class="${this.tab==='play'?'active':''}">PLAY</button><button data-dream-tab="ranked" class="${this.tab==='ranked'?'active':''}">RANKED</button><button data-dream-tab="events" class="${this.tab==='events'?'active':''}">EVENTS</button><button data-dream-tab="packs" class="${this.tab==='packs'?'active':''}">PACKS</button><button data-dream-tab="objectives" class="${this.tab==='objectives'?'active':''}">OBJECTIVES</button><button data-dream-tab="collection" class="${this.tab==='collection'?'active':''}">COLLECTION</button><button data-dream-tab="inventory" class="${this.tab==='inventory'?'active':''}">INVENTORY</button></nav><main class="dream-content">${content}</main>${this.reveal?this.revealMarkup():''}</div>`;
  }
  homeMarkup(rank,owned){const s=this.state,team=this.teamFromCards(s.customTeam.name,s.squad,s.customTeam.homeKit,s.customTeam.badge),next=(this.meta?.events||[])[0];return `<section class="dream-hero"><div><span class="eyebrow">YOUR CUSTOM LSL SQUAD</span><h2>${e(s.customTeam.name)}</h2><p>Build a seven-a-side dream team from real LSL seasons, then take it into CPU Ranked matches and original events.</p><button class="dream-cta" data-dream-tab="my-team">OPEN MY TEAM ↗</button></div><div class="dream-badge"><img src="${e(s.customTeam.badge)}" alt=""><strong>${team.overall??'—'}</strong><small>TEAM OVR</small></div></section><div class="dream-grid dream-home-grid"><article class="dream-panel dream-feature"><span class="eyebrow">FEATURED EVENT</span><h3>${e(next?.name||'LSL TEAM OF THE YEAR')}</h3><p>${e(next?.description||'Play CPU fixtures for rewards.')}</p><button data-dream-tab="events" class="secondary">VIEW EVENT</button></article>${this.rankMarkup()}<article class="dream-panel"><span class="eyebrow">COLLECTION</span><strong class="dream-big-number">${owned}</strong><p>LSL cards collected across 2024 · 2025 · 2026</p><button data-dream-tab="collection" class="secondary">VIEW COLLECTION</button></article><article class="dream-panel dream-account-panel"><span class="eyebrow">ACCOUNT</span><h3>TROPHIES &amp; RECORDS</h3><p>Carry your best moments across every LSL mode.</p><div class="dream-account-links"><a href="./account.html#trophies" class="secondary">TROPHIES</a><a href="./account.html#records" class="secondary">RECORDS</a></div></article><article class="dream-panel dream-lineup-mini"><span class="eyebrow">CURRENT LINEUP · ${e(s.customTeam.name)}</span><div>${s.squad.slice(0,7).map((key,index)=>{const c=this.card(key);return `<span><b>${index===0?'GK':index<3?'DEF':index<5?'MID':'FWD'}</b>${e(c?.name||'Player')}</span>`;}).join('')}</div></article></div>`;}
  teamMarkup(){const s=this.state,m=this.teamMetrics(s.squad),badges=this.badgeOptions();return `<section class="dream-section-head"><div><span class="eyebrow">MY TEAM</span><h2>Build your seven.</h2><p>Drag a collected card onto a field slot, choose a new formation, and save the squad that represents your LSL Dream F.C.</p></div><button class="dream-cta" data-dream-save>SAVE SQUAD</button></section><div class="dream-team-editor"><aside class="dream-card-sidebar"><label class="dream-input-label">TEAM NAME<input id="dream-team-name" value="${e(s.customTeam.name)}" maxlength="26"></label><label class="dream-input-label">LSL BADGE<select id="dream-team-badge">${badges.map(item=>`<option value="${e(item.logo)}" ${item.logo===s.customTeam.badge?'selected':''}>${e(item.name)}</option>`).join('')}</select></label><div class="dream-color-row"><label>HOME <input type="color" data-dream-color="homeKit" value="${e(s.customTeam.homeKit)}"></label><label>AWAY <input type="color" data-dream-color="awayKit" value="${e(s.customTeam.awayKit)}"></label><label>PRIMARY <input type="color" data-dream-color="primary" value="${e(s.customTeam.primary)}"></label></div><h3>COLLECTED CARDS</h3><div class="dream-card-list">${s.collection.map(key=>this.cardMarkup(key,s.squad.includes(key))).join('')}</div></aside><div class="dream-pitch"><div class="dream-pitch-lines"></div>${s.squad.map((key,index)=>`<div class="dream-slot" data-dream-slot="${index}" style="--x:${[16,32,32,51,51,73,73][index]}%;--y:${[50,28,72,28,72,36,64][index]}%"><span>${index===0?'GK':index<3?'DEF':index<5?'MID':'FWD'}</span>${this.cardMarkup(key,true)}</div>`).join('')}</div></div><div class="dream-team-meta"><span><b>${m.overall}</b> TEAM OVR</span><span><b>${m.attack}</b> ATT</span><span><b>${m.mid}</b> MID</span><span><b>${m.defence}</b> DEF</span><span><b>${m.keeper}</b> GK</span><span><b>${money(s.collection.length)}</b> CARDS</span><button data-open-formation class="secondary">FORMATION BUILDER</button></div>`;}
  playMarkup(){return `<section class="dream-section-head"><div><span class="eyebrow">PLAY · CPU ONLY</span><h2>Take the dream team to matchday.</h2><p>Every fixture is single-player against an LSL CPU squad. No matchmaking, no public multiplayer, no live opponents.</p></div></section><div class="dream-play-grid"><article class="dream-play-card featured"><span class="eyebrow">RANKED MATCH</span><h3>Climb the LSL ladder.</h3><p>${e(this.rank().name)} · ${money(this.state.ranked.rp)} RP. Win matches to earn RP, coins and draft vouchers.</p><button class="dream-cta" data-dream-ranked>PLAY RANKED ↗</button></article>${(this.meta?.events||[]).slice(0,3).map(item=>`<article class="dream-play-card"><span class="eyebrow">EVENT FIXTURE</span><h3>${e(item.name)}</h3><p>${e(item.description)}</p><button class="secondary" data-dream-event="${e(item.id)}">PLAY EVENT</button></article>`).join('')}</div>`;}
  eventsMarkup(){return `<section class="dream-section-head"><div><span class="eyebrow">EVENTS · PLAY TO EARN</span><h2>Chapters with a finish line.</h2><p>Complete CPU fixtures, earn event points and move along each visible reward path.</p></div><button class="dream-cta" data-dream-tab="play">PLAY NOW</button></section><div class="dream-event-list">${(this.meta?.events||[]).map(item=>`<article class="dream-event-card" style="--accent:${item.accent}"><div><span class="eyebrow">LSL EVENT · ${money(this.state.eventPoints[item.id]||0)} POINTS</span><h3>${e(item.name)}</h3><p>${e(item.description)}</p></div><div class="dream-reward-path">${(item.steps||[]).map(step=>`<span><b>${money(step.points)}</b>${e(step.reward)}</span>`).join('')}</div><button class="secondary" data-dream-event="${e(item.id)}">PLAY CHAPTER</button></article>`).join('')}</div>`;}
  packsMarkup(){const packs=this.meta?.packs||[];return `<section class="dream-section-head"><div><span class="eyebrow">PACKS · REWARDS</span><h2>Open the next chapter.</h2><p>Odds are shown before you open. Base cards always use the player's published LSL OVR; special cards are capped at 100.</p></div><span class="dream-balance">🎟 ${money(this.state.vouchers)} vouchers</span></section><div class="dream-pack-grid">${packs.map(pack=>`<article class="dream-pack"><div class="dream-pack-art"><span>${e(pack.name.split(' ')[0])}</span><strong>LSL</strong></div><h3>${e(pack.name)}</h3><p>${e(pack.guarantee||'See odds')}${pack.cost?` · ${money(pack.cost)} ${e(pack.currency)}`:' · REWARD'}</p><small>Odds: ${Object.entries(pack.odds||{}).map(([k,v])=>e(k)+' '+this.oddsText(v)).join(' · ')}</small><button class="dream-cta" data-dream-open-pack="${e(pack.id)}">${pack.cost?'OPEN PACK':'CLAIM PACK'}</button></article>`).join('')}</div>`;}
  objectivesMarkup(){return `<section class="dream-section-head"><div><span class="eyebrow">OBJECTIVES</span><h2>Small steps. Better cards.</h2><p>Daily, weekly, seasonal and event goals make every CPU match count.</p></div></section><div class="dream-objectives">${(this.meta?.objectives||[]).map(item=>{const progress=Math.min(item.target,Number(this.state.objectives[item.id]||0));return `<article><span class="eyebrow">${e(item.group)}</span><h3>${e(item.title)}</h3><div class="dream-progress"><i style="width:${progress/item.target*100}%"></i></div><small>${progress} / ${item.target} · ${e(item.reward)}</small></article>`;}).join('')}</div>`;}
  collectionMarkup(){const s=this.state,keys=[...new Set(this.cards.map(c=>c.cardKey))],owned=new Set(s.collection);return `<section class="dream-section-head"><div><span class="eyebrow">COLLECTION</span><h2>Every LSL season in one club.</h2><p>Real roster data from 2024, 2025 and 2026. Unrated players remain marked until an official LSL OVR is available.</p></div><span class="dream-balance">${owned.size} / ${keys.length} OWNED</span></section><div class="dream-collection-grid">${keys.map(key=>this.cardMarkup(key,owned.has(key))||'').join('')}</div>`;}
  inventoryMarkup(){const s=this.state,duplicates=s.collection.filter((key,index,list)=>list.indexOf(key)!==index),duplicateKeys=[...new Set(duplicates)];return `<section class="dream-section-head"><div><span class="eyebrow">INVENTORY</span><h2>Keep your club organized.</h2><p>Duplicates stay useful. Lock valuable cards, use extras in future exchanges, and track the rewards you have earned.</p></div></section><div class="dream-inventory-grid"><article><span class="eyebrow">DUPLICATES</span><strong>${duplicates.length}</strong><small>cards ready for exchange</small>${duplicateKeys.slice(0,5).map(key=>`<button class="dream-inventory-card" data-dream-lock="${e(key)}">${e(this.card(key)?.name||'LSL card')} · ${s.locked.includes(key)?'LOCKED':'LOCK'}</button>`).join('')}</article><article><span class="eyebrow">RANKED STREAK</span><strong>${this.state.ranked.streak||0}</strong><small>small RP bonuses at 3 · 5 · 10 wins</small></article><article><span class="eyebrow">UNRATED FLAGS</span><strong>${this.cards.filter(c=>c.unrated&&s.collection.includes(c.cardKey)).length}</strong><small>official OVR still needed</small></article></div>`;}
  revealMarkup(){const r=this.reveal;if(r.message)return `<div class="dream-reveal-overlay"><div class="dream-reveal-card"><span class="eyebrow">LSL DREAM F.C.</span><h2>${e(r.title)}</h2><p>${e(r.message)}</p><button class="primary" data-dream-close-reveal>OK</button></div></div>`;if(r.detail){const c=r.detail,stats=playerRatings(c.source||c);return `<div class="dream-reveal-overlay"><div class="dream-reveal-card dream-detail-card"><span class="eyebrow">PLAYER CARD · ${e(c.programName||'BASE MT')}</span><span class="dream-card-ovr">${c.overall??'—'}</span><span class="dream-card-position">${e(c.position||'PLAYER')}</span><h2>${e(c.name||'LSL Player')}</h2><p>${e(c.teamName||'LSL')} · SEASON ${e(c.season||'—')} · JERSEY #${c.jersey??'—'}</p><div class="dream-detail-stats"><span><b>${c.overall??'—'}</b> OVR</span><span><b>${c.source?.playstyle?.label?e(c.source.playstyle.label):'—'}</b> PLAYSTYLE</span>${[['SPD','speed'],['SHO','shooting'],['PAS','passing'],['DRI','dribbling'],['DEF','defending'],['STA','stamina'],['GK','goalkeeping']].map(([label,key])=>`<span><b>${stats[key]}</b> ${label}</span>`).join('')}</div><small>Game ratings are derived from the published LSL OVR/profile. Muhummud Teli is the fastest player profile.</small><button class="primary" data-dream-close-reveal>CLOSE</button></div></div>`;}const c=r.card;return `<div class="dream-reveal-overlay"><div class="dream-reveal-card dream-reveal-player"><span class="eyebrow">${e(r.pack.name)} · CARD REVEAL</span><div class="dream-reveal-glow"></div><span class="dream-card-ovr">${c?.overall??'—'}</span><span class="dream-card-position">${e((c?.position||'PLAYER').slice(0,3).toUpperCase())}</span><h2>${e(c?.name||'LSL Player')}</h2><p>${e(c?.teamName||'LSL')} · #${c?.jersey??'—'} · ${e(c?.programName||'BASE MT')}</p><small>Actual LSL OVR source · ${e(c?.season||'—')}</small><div class="dream-reveal-actions"><button class="primary" data-dream-close-reveal>ADD TO CLUB</button><button class="text-button" data-dream-close-reveal>SKIP</button></div></div></div>`;}
}
