import {CloudAccount} from './cloud-account.js';
import {filterMatches,summarize} from './match-history.js';
import {navigation,esc,modes,difficulties,summaryCards,matchCard,trendChart} from './history-view.js';
const root=document.querySelector('#history-app'),service=new CloudAccount();let history=[],profile=null,warning='',visible=20;const filters={};
const options=(key,values)=>`<label>${key}<select name="${key.toLowerCase()}"><option value="">All</option>${[...new Set(values.filter(Boolean))].sort().map(v=>`<option>${esc(v)}</option>`).join('')}</select></label>`;
function render(){
  root.innerHTML=navigation('history')+`<main class="hub-main"><div class="hub-heading"><span class="eyebrow">YOUR MATCHDAY ARCHIVE</span><h1>HISTORY</h1><p>Every completed match. Every moment that counts.</p></div>${!profile?'<section class="hub-panel"><h2>Your history starts here</h2><p>Sign in to keep match reports across every game mode.</p><a class="hub-button primary" href="./index.html#account">CREATE ACCOUNT / SIGN IN</a></section>':`${warning?`<p class="hub-notice" role="status">${esc(warning)}</p>`:''}<div id="all-time-summary">${summaryCards(summarize(history))}</div><p class="muted-copy">All-time totals from available reports. Points in records mean goals + assists.</p><form class="history-filters hub-panel" id="history-filters"><label class="filter-search">Search<input name="search" type="search" placeholder="Team, player or match…"></label><label>Result<select name="result"><option value="all">All results</option><option value="wins">Wins</option><option value="draws">Draws</option><option value="losses">Losses</option></select></label><label>Game mode<select name="mode">${modes()}</select></label>${options('Team',history.map(r=>r.teams?.[0]))}${options('Opponent',history.map(r=>r.teams?.[1]))}${options('Season',history.map(r=>r.season))}<label>CPU difficulty<select name="difficulty">${difficulties()}</select></label><label>From<input type="date" name="from"></label><label>To<input type="date" name="to"></label><label>Sort<select name="sort"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="goals">Most goals</option><option value="margin">Biggest win</option></select></label><button type="reset" class="hub-button">RESET FILTERS</button><button type="button" class="hub-button" id="sync-history">RETRY SYNC</button></form><div id="history-trend"></div><div class="section-head"><h2>Match reports</h2><span id="history-count" aria-live="polite"></span></div><div id="history-list" class="history-list"></div><button class="hub-button" id="more-history">LOAD MORE</button>`}</main>`;
  if(!profile)return;
  const form=root.querySelector('form');for(const [key,value]of Object.entries(filters)){if(form.elements.namedItem(key))form.elements.namedItem(key).value=value;}form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('input',()=>{Object.assign(filters,Object.fromEntries(new FormData(form)));visible=20;results();});form.addEventListener('reset',()=>{for(const key of Object.keys(filters))delete filters[key];visible=20;results();});root.querySelector('#more-history').onclick=()=>{visible+=20;results();};root.querySelector('#sync-history').onclick=()=>load();results();
}
function results(){const list=filterMatches(history,filters);root.querySelector('#history-count').textContent=`${list.length} matches`;root.querySelector('#history-list').innerHTML=list.slice(0,visible).map(matchCard).join('')||'<div class="hub-panel">No matches match these filters.</div>';root.querySelector('#history-trend').innerHTML=trendChart(list);root.querySelector('#more-history').hidden=visible>=list.length;}
async function load(){await service.ready;profile=service.profile;warning='';if(profile){try{await service.flushHistory();}catch{warning='Some matches are saved on this device and waiting to sync. Check your connection and publish the updated Firestore rules.';}try{history=await service.getHistory(profile);if(history.archiveIncomplete)warning='Cloud archive unavailable. Showing locally pending reports and retained legacy entries. Publish updated Firestore rules or retry your connection.';const missing=Math.max(0,(profile.stats?.matches||0)-history.length);if(missing)warning+=` ${missing} older matches have totals only; their original reports were not retained.`;}catch{history=profile.history||[];warning='Cloud archive unavailable. Showing older profile entries only. Publish the updated Firestore rules, then retry.';}}render();}
root.innerHTML=navigation('history')+'<main class="hub-main"><p role="status">Loading your match history…</p></main>';load().catch(error=>{root.innerHTML=navigation('history')+`<main class="hub-main"><p class="hub-notice">${esc(error.message)}</p><a href="./history.html">Retry</a></main>`;});
