import {MODE_LABELS,DIFFICULTY_LABELS,normalizeDifficulty,matchMetrics,RECORDS} from './match-history.js';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const clock=v=>v==null?'Not recorded':`${Math.floor(v/60)}:${String(Math.floor(v%60)).padStart(2,'0')}`;
export const date=v=>new Date(v).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
export function navigation(active){return `<site-nav active="${active==='index'?'home':['charts','account'].includes(active)?active:'account'}"></site-nav>`;}
export const difficulties=(selected='all')=>Object.entries(DIFFICULTY_LABELS).map(([key,label])=>`<option value="${key}" ${key===selected?'selected':''}>${label}</option>`).join('');
export const modes=(selected='all')=>Object.entries(MODE_LABELS).map(([k,v])=>`<option value="${k}" ${k===selected?'selected':''}>${v}</option>`).join('');
export function summaryCards(s){return `<div class="hub-summary">${[['Matches','matches'],['Wins','wins'],['Draws','ties'],['Losses','losses'],['Goals for','goals'],['Goals against','goalsAgainst'],['Win %','winPercent']].map(([label,key])=>`<article><small>${label}</small><strong>${key==='winPercent'?(s[key]||0).toFixed(1)+'%':s[key]||0}</strong></article>`).join('')}</div>`;}
export const opponentLabel=r=>['local','account'].includes(r.opponent?.type)?`${r.opponent.type==='account'?'Player':'Local player'} — ${r.opponent.accountName||r.opponent.name||'Name not recorded'}`:`CPU — ${r.opponent?.difficulty?(DIFFICULTY_LABELS[normalizeDifficulty(r.opponent.difficulty)]||r.opponent.difficulty):'difficulty not recorded'}`;
function playerName(p){return `${esc(p.name)}${p.jersey!=null?' #'+esc(p.jersey):''}`;}
function formation(f){if(!f?.length)return 'Not recorded';const counts={};for(const p of f)if(p.role!=='GK')counts[p.role]=(counts[p.role]||0)+1;return ['DEF','MID','FWD'].map(role=>counts[role]||0).join('–');}
export function matchReport(r){
  const u=r.stats?.user||{},c=r.stats?.cpu||{},pos=(u.possession||0)+(c.possession||0),percent=s=>pos?Math.round((s.possession||0)/pos*100)+'%':'—',accuracy=s=>s.passes?Math.round((s.completed||0)/s.passes*100)+'%':'—';
  const rows=[['Shots','shots'],['Shots on target','onTarget'],['Possession',percent],['Passes','passes'],['Pass accuracy',accuracy],['Saves','saves'],['Corners','corners'],['Fouls','fouls'],['Yellow cards','yellows'],['Red cards','reds'],['Penalties awarded','penalties'],['Penalties scored','penaltiesScored'],['Penalties saved','penaltiesSaved'],['Free-kick goals','freeKickGoals'],['Corner goals','cornerGoals'],['Substitutions','substitutions']];
  const val=(s,key)=>typeof key==='function'?key(s):(s[key]??'—');
  return `<div class="match-report">${r.schemaVersion!==2?'<p class="hub-notice">Legacy report: some details were not recorded. Missing statistics are shown as —.</p>':''}<p>Played by <strong>${esc(r.accountName||'Account name not recorded')}</strong> · ${esc(opponentLabel(r))} · ${clock(r.duration)} played${r.scheduledDuration?' / '+clock(r.scheduledDuration)+' scheduled':''}</p><div class="report-columns"><section><h3>Match statistics</h3><table class="report-table"><thead><tr><th>${esc(r.teams?.[0])}</th><th>Statistic</th><th>${esc(r.teams?.[1])}</th></tr></thead><tbody>${rows.map(([label,key])=>`<tr><td>${esc(val(u,key))}</td><th>${label}</th><td>${esc(val(c,key))}</td></tr>`).join('')}</tbody></table></section><section><h3>Goal timeline</h3>${r.goals?.length?`<ol class="goal-timeline">${r.goals.map(g=>`<li><b>${clock(g.time)}</b><div><strong>${playerName(g)}${g.ownGoal?' (own goal)':''}</strong><small>${esc(r.teams?.[g.team])}${g.assist?' · Assist: '+esc(g.assist)+(g.assistJersey!=null?' #'+esc(g.assistJersey):''):''}${g.setPiece?' · '+esc(g.setPiece):''}</small></div></li>`).join('')}</ol>`:'<p>No goals recorded.</p>'}<h3>Player of the Match</h3><p>${r.playerOfMatch?playerName(r.playerOfMatch)+' · '+esc(r.teams?.[r.playerOfMatch.team]):'Not recorded'}</p><h3>Substitutions</h3>${r.substitutions?.length?r.substitutions.map(s=>`<p>${clock(s.time)} · ${esc(r.teams?.[s.team])}<br>${esc(s.out)} ${s.outJersey!=null?'#'+esc(s.outJersey):''} → ${esc(s.in)} ${s.inJersey!=null?'#'+esc(s.inJersey):''}</p>`).join(''):'<p>'+((u.substitutions||c.substitutions)?'Player details not recorded.':'No substitutions recorded.')+'</p>'}</section></div><div class="report-columns">${[0,1].map(team=>`<section><h3>${esc(r.teams?.[team])} · Lineup</h3><p>Start: ${formation(r.startingFormations?.[team])} → Final: ${formation(r.finalFormations?.[team])}</p>${r.startingLineups?.[team]?.length?`<ul class="lineup-report">${r.startingLineups[team].map(p=>`<li><b>${esc(p.position)}</b> ${playerName(p)}</li>`).join('')}</ul><details><summary>Final positions</summary><ul class="lineup-report">${(r.finalLineups?.[team]||[]).map(p=>`<li><b>${esc(p.position)}</b> ${playerName(p)}</li>`).join('')}</ul></details>`:'<p>Lineup not recorded.</p>'}</section>`).join('')}</div>${r.players?.length?`<h3>Individual match statistics</h3><div class="table-scroll"><table class="report-table player-table"><thead><tr><th>Player</th><th>Team</th><th>Pos</th><th>Goals</th><th>Assists</th><th>Shots</th><th>On target</th><th>Passes</th><th>Tackles</th><th>Saves</th><th>YC / RC</th></tr></thead><tbody>${r.players.map(p=>`<tr><th>${playerName(p)}</th><td>${esc(r.teams?.[p.team])}</td><td>${esc(p.position)}</td>${['goals','assists','shots','onTarget','passes','tackles','saves'].map(k=>`<td>${p[k]??'—'}</td>`).join('')}<td>${esc(p.yellows||0)} / ${esc(p.reds||0)}</td></tr>`).join('')}</tbody></table></div>`:''}</div>`;
}
export function matchCard(r){const m=matchMetrics(r),result=m.wins?'Win':m.ties?'Draw':'Loss';return `<details class="history-match"><summary><span class="result-pill ${result.toLowerCase()}">${result}</span><span class="match-identity"><strong>${esc(r.teams?.[0])} <em>vs</em> ${esc(r.teams?.[1])}</strong><small>${esc(date(r.date))} · ${esc(MODE_LABELS[r.mode]||r.modeLabel)}${r.season?' · '+esc(r.season):''}${r.competition?.stage?' · '+esc(r.competition.stage):''}</small><small>Played by ${esc(r.accountName||'Account name not recorded')} · ${esc(opponentLabel(r))} · ${clock(r.duration)}${r.pending?' · Pending sync':''}</small></span><b class="match-score">${r.score?.join(' – ')}</b><span aria-hidden="true">⌄</span></summary>${matchReport(r)}</details>`;}
export function recordGrid(entries){return `<div class="record-holder-grid">${RECORDS.map(([key,label,,lower])=>{const item=entries[key],r=item?.match,value=!item?'—':lower?clock(item.value):['possession','accuracy'].includes(key)?item.value.toFixed(1)+'%':item.value;return `<article class="record-holder"><small>${label}</small><strong>${value}</strong>${item?`<a href="./account.html?user=${encodeURIComponent(item.uid||'')}">${esc(item.holder||'Your record')}</a>${item.player?`<span>${esc(item.player)}</span>`:''}<span>${r?esc(r.teams?.join(' vs ')):'Across recorded matches'}</span><small>${r?esc(date(r.date))+' · '+esc(MODE_LABELS[r.mode])+' · '+esc(opponentLabel(r)):esc(item.modeLabel||'Selected mode')}</small>`:'<span>No qualifying result yet</span>'}</article>`;}).join('')}</div>`;}
export function trendChart(records){const recent=[...records].sort((a,b)=>a.date-b.date).slice(-16),max=Math.max(1,...recent.flatMap(r=>r.score||[0]));return `<section class="hub-panel"><div class="section-head"><h2>Recent scoring form</h2><small>Last ${recent.length} matches · For / Against</small></div>${recent.length?`<div class="trend-chart" role="img" aria-label="Goals for and against in recent matches">${recent.map((r,i)=>`<div class="trend-column"><div><i style="height:${r.score[0]/max*100}%" title="Goals for: ${esc(r.score[0])}"></i><i style="height:${r.score[1]/max*100}%" title="Goals against: ${esc(r.score[1])}"></i></div><small>${i+1}</small><span>${r.score.join('–')}</span></div>`).join('')}</div><p class="chart-legend"><i></i> Goals for <i></i> Goals against · oldest to newest</p>`:'<p>Complete a match to start your scoring trend.</p>'}</section>`;}
